-- 300 rows · batch3 — regenerate: python3 supabase/generate_questions_300_batch3.py > supabase/questions_seed_300_batch3.sql

INSERT INTO questions (difficulty, question_text, options, correct_answer_old, correct_index, explanation) VALUES
('elementary', 'My cousins ___ in the band.', '["A. am", "B. is", "C. are", "D. be"]'::jsonb, 'C', 2, '複數 cousins 用 are。'),
('elementary', 'Uncle Joe ___ fishing on Sundays.', '["A. go", "B. goes", "C. going", "D. went"]'::jsonb, 'B', 1, '習慣第三人稱 goes。'),
('elementary', 'The puppies ___ hungry.', '["A. am", "B. is", "C. are", "D. be"]'::jsonb, 'C', 2, '複數 puppies 用 are。'),
('elementary', '___ there any chairs free?', '["A. Are", "B. Is", "C. Am", "D. Do"]'::jsonb, 'A', 0, '複數 chairs 用 Are there。'),
('elementary', '___ your brother at home?', '["A. Are", "B. Is", "C. Am", "D. Do"]'::jsonb, 'B', 1, '單數 brother 用 Is。'),
('elementary', 'These socks ___ mine.', '["A. am", "B. is", "C. are", "D. be"]'::jsonb, 'C', 2, 'these 複數用 are。'),
('elementary', 'I ___ a good idea.', '["A. have", "B. has", "C. having", "D. had"]'::jsonb, 'A', 0, 'I have。'),
('elementary', 'She ___ a red bicycle.', '["A. have", "B. has", "C. having", "D. had"]'::jsonb, 'B', 1, 'she has。'),
('elementary', 'We ___ finished lunch.', '["A. has", "B. have", "C. having", "D. had"]'::jsonb, 'C', 2, 'We have + 過去分詞。'),
('elementary', 'He ___ not like peppers.', '["A. do", "B. does", "C. is", "D. are"]'::jsonb, 'B', 1, '第三人稱否定 does。'),
('elementary', '___ you know her name?', '["A. Do", "B. Does", "C. Is", "D. Are"]'::jsonb, 'A', 0, 'you 搭配 Do。'),
('elementary', 'It ___ not rain much here.', '["A. do", "B. does", "C. is", "D. are"]'::jsonb, 'B', 1, '天氣主詞 it + does not。'),
('elementary', 'They ___ not want dessert.', '["A. do", "B. does", "C. don''t", "D. doesn''t"]'::jsonb, 'C', 2, '複數否定 don''t want。'),
('elementary', 'She ___ TV every evening.', '["A. watch", "B. watches", "C. watching", "D. watched"]'::jsonb, 'B', 1, '習慣 watches。'),
('elementary', 'I ___ breakfast at eight.', '["A. eat", "B. eats", "C. eating", "D. ate"]'::jsonb, 'A', 0, 'I + eat。'),
('elementary', 'Last year we ___ to Italy.', '["A. go", "B. goes", "C. going", "D. went"]'::jsonb, 'D', 3, 'last year 過去 went。'),
('elementary', 'Listen! The baby ___ .', '["A. cry", "B. cries", "C. is crying", "D. cried"]'::jsonb, 'C', 2, 'Listen 現在進行。'),
('elementary', 'Right now they ___ chess.', '["A. play", "B. plays", "C. are playing", "D. played"]'::jsonb, 'B', 1, 'right now 進行。'),
('elementary', 'I ___ never ___ a camel.', '["A. have / see", "B. have / seen", "C. has / seen", "D. had / see"]'::jsonb, 'C', 2, '現在完成 have seen。'),
('elementary', 'He ___ already ___ his bag.', '["A. have / pack", "B. has / packed", "C. has / packing", "D. had / pack"]'::jsonb, 'B', 1, 'has packed。'),
('elementary', '___ you ever ___ sushi?', '["A. Have / tried", "B. Has / tried", "C. Did / tried", "D. Do / try"]'::jsonb, 'A', 0, 'Have you ever tried。'),
('elementary', 'She could swim when she ___ five.', '["A. am", "B. was", "C. were", "D. is"]'::jsonb, 'B', 1, '過去年齡 was five。'),
('elementary', 'We ___ visit Grandma tomorrow.', '["A. am", "B. is", "C. will", "D. was"]'::jsonb, 'C', 2, '未來 will。'),
('elementary', 'I think it ___ be cold tonight.', '["A. will", "B. might", "C. must", "D. can"]'::jsonb, 'B', 1, '可能 might。'),
('elementary', 'You ___ not run in the hallway.', '["A. must", "B. might", "C. could", "D. should"]'::jsonb, 'A', 0, '禁止 must not。'),
('elementary', '___ I borrow your eraser?', '["A. Must", "B. Should", "C. May", "D. Need"]'::jsonb, 'C', 2, '禮貌請求 May I。'),
('elementary', 'There ___ little water in the bottle.', '["A. are", "B. is", "C. be", "D. am"]'::jsonb, 'B', 1, 'little water 不可數 is。'),
('elementary', 'How ___ pencils do you need?', '["A. much", "B. many", "C. long", "D. often"]'::jsonb, 'B', 1, '可數 pencils many。'),
('elementary', 'How ___ sugar do we need?', '["A. much", "B. many", "C. often", "D. far"]'::jsonb, 'A', 0, '不可數 sugar much。'),
('elementary', 'Give me ___ umbrella; it''s raining.', '["A. a", "B. an", "C. the", "D. no article"]'::jsonb, 'C', 2, 'umbrella 母音 an。'),
('elementary', 'This is ___ useful tool.', '["A. a", "B. an", "C. the", "D. no article"]'::jsonb, 'A', 0, 'useful 子音音 a。'),
('elementary', '___ moon looks bright tonight.', '["A. A", "B. An", "C. The", "D. no article"]'::jsonb, 'C', 2, '天體 the moon。'),
('elementary', 'She plays the piano ___ than I do.', '["A. good", "B. better", "C. best", "D. more good"]'::jsonb, 'B', 1, 'than 比較 better。'),
('elementary', 'That was the ___ day ever!', '["A. bad", "B. worse", "C. worst", "D. more bad"]'::jsonb, 'C', 2, 'ever 最高級 worst。'),
('elementary', 'He drives ___ .', '["A. careful", "B. carefully", "C. carefulness", "D. more careful"]'::jsonb, 'B', 1, '修飾動詞副詞 carefully。'),
('elementary', '___ me your book, please.', '["A. Pass", "B. Passing", "C. To pass", "D. Passed"]'::jsonb, 'A', 0, '祈使原形 Pass。'),
('elementary', 'She is fond ___ animals.', '["A. in", "B. of", "C. at", "D. for"]'::jsonb, 'B', 1, 'be fond of。'),
('elementary', 'We''re proud ___ our team.', '["A. in", "B. at", "C. of", "D. for"]'::jsonb, 'C', 2, 'be proud of。'),
('elementary', 'Wait ___ me at the gate.', '["A. for", "B. to", "C. at", "D. on"]'::jsonb, 'A', 0, 'wait for。'),
('elementary', 'The keys are ___ the drawer.', '["A. in", "B. on", "C. at", "D. to"]'::jsonb, 'C', 2, '在抽屜裡 in。'),
('elementary', 'We''ll see you ___ Friday.', '["A. in", "B. on", "C. at", "D. by"]'::jsonb, 'B', 1, '星期 on Friday。'),
('elementary', '___ July it is often hot.', '["A. In", "B. On", "C. At", "D. By"]'::jsonb, 'A', 0, '月份用 in：in July。'),
('elementary', 'She arrived ___ school early.', '["A. at", "B. in", "C. on", "D. to"]'::jsonb, 'A', 0, 'at school。'),
('elementary', 'What''s the opposite of ''tall''?', '["A. wide", "B. short", "C. loud", "D. sweet"]'::jsonb, 'B', 1, 'tall 反義 short。'),
('elementary', 'One week has ___ days.', '["A. five", "B. six", "C. seven", "D. eight"]'::jsonb, 'C', 2, '一週七天。'),
('elementary', 'Boiling water is ___ degrees Celsius.', '["A. 50", "B. 100", "C. 0", "D. 32"]'::jsonb, 'B', 1, '沸點攝氏 100。'),
('elementary', 'Penguins cannot ___.', '["A. run fast", "B. fly", "C. swim", "D. slide"]'::jsonb, 'B', 1, '企鵝不會飛。'),
('elementary', 'You write on paper with a ___.', '["A. spoon", "B. fork", "C. pen", "D. cup"]'::jsonb, 'C', 2, '筆寫字。'),
('elementary', 'We smell with our ___.', '["A. eyes", "B. ears", "C. nose", "D. feet"]'::jsonb, 'B', 1, '鼻子嗅覺。'),
('elementary', 'This soup smells ___.', '["A. nicely", "B. nice", "C. niceness", "D. nicer"]'::jsonb, 'A', 0, 'smell + 形容詞 nice。'),
('elementary', 'The students look ___.', '["A. happily", "B. tired", "C. tiring", "D. tiredly"]'::jsonb, 'B', 1, 'look + 形容詞 tired。'),
('elementary', '___ time is it?', '["A. Who", "B. Which", "C. What", "D. Whose"]'::jsonb, 'C', 2, 'What time。'),
('elementary', '___ bag is this — yours or mine?', '["A. Who", "B. Which", "C. Whose", "D. What"]'::jsonb, 'B', 1, '誰的 Whose。'),
('elementary', 'Let''s ___ a short break.', '["A. take", "B. takes", "C. taking", "D. took"]'::jsonb, 'A', 0, 'Let''s + 原形。'),
('elementary', 'Please don''t ___ loudly in the library.', '["A. talk", "B. talks", "C. talking", "D. talked"]'::jsonb, 'A', 0, 'Don''t + 原形。'),
('elementary', 'She enjoys ___ cartoons.', '["A. watch", "B. to watch", "C. watching", "D. watched"]'::jsonb, 'C', 2, 'enjoy + 動名詞。'),
('elementary', 'He stopped ___ a drink.', '["A. have", "B. to have", "C. having", "D. had"]'::jsonb, 'B', 1, '停下來去做 stop to have。'),
('elementary', 'They decided ___ the early train.', '["A. catch", "B. to catch", "C. catching", "D. caught"]'::jsonb, 'A', 0, 'decide to catch。'),
('elementary', 'I''m not used ___ up this early.', '["A. get", "B. to get", "C. to getting", "D. getting"]'::jsonb, 'C', 2, 'be used to + 動名詞。'),
('elementary', 'There is ___ milk in the fridge.', '["A. a few", "B. a little", "C. many", "D. several"]'::jsonb, 'B', 1, '不可數 a little。'),
('elementary', 'She has ___ friends in this city.', '["A. much", "B. a lot of", "C. little", "D. a little"]'::jsonb, 'C', 2, '可數 friends a lot of。'),
('elementary', '___ you mind closing the window?', '["A. Would", "B. Do", "C. Are", "D. Will"]'::jsonb, 'A', 0, 'Would you mind + V-ing。'),
('elementary', 'Thanks ___ your help.', '["A. for", "B. to", "C. of", "D. at"]'::jsonb, 'B', 1, 'thanks for。'),
('elementary', 'He is married ___ a doctor.', '["A. with", "B. to", "C. for", "D. at"]'::jsonb, 'B', 1, 'married to。'),
('elementary', 'The bus leaves ___ 3 p.m.', '["A. in", "B. on", "C. at", "D. by"]'::jsonb, 'C', 2, '時刻 at 3 p.m.。'),
('elementary', 'I was born ___ 2010.', '["A. in", "B. on", "C. at", "D. by"]'::jsonb, 'B', 1, '年份 in 2010。'),
('elementary', 'She cut the paper ___ scissors.', '["A. by", "B. with", "C. use", "D. using"]'::jsonb, 'B', 1, 'with scissors。'),
('elementary', 'This gift is ___ you.', '["A. to", "B. for", "C. from", "D. at"]'::jsonb, 'A', 0, '給某人 for you。'),
('elementary', 'He died ___ a serious illness.', '["A. of", "B. from", "C. by", "D. with"]'::jsonb, 'B', 1, '死於疾病 die of。'),
('elementary', '___! You dropped your wallet.', '["A. Hey", "B. Hear", "C. Listen to", "D. Sound"]'::jsonb, 'C', 2, '引起注意 Hey。'),
('elementary', 'Could I have ___ water, please?', '["A. any", "B. some", "C. many", "D. few"]'::jsonb, 'A', 0, '禮貌請求 some。'),
('elementary', 'I have ___ friends than she does.', '["A. much", "B. more", "C. most", "D. many"]'::jsonb, 'B', 1, 'than more。'),
('elementary', 'This is ___ interesting story.', '["A. a", "B. an", "C. the", "D. no article"]'::jsonb, 'C', 2, 'interesting 母音 an。'),
('elementary', 'Neither parent ___ angry.', '["A. are", "B. is", "C. were", "D. be"]'::jsonb, 'A', 0, 'neither + 單數 is。'),
('elementary', 'Few students ___ absent.', '["A. was", "B. were", "C. is", "D. be"]'::jsonb, 'B', 1, 'few students 複數 were。'),
('junior', 'If you heat ice, it ___ .', '["A. melt", "B. melts", "C. melted", "D. melting"]'::jsonb, 'B', 1, '科學真理 if + 現在 melts。'),
('junior', 'Unless we leave now, we ___ the show.', '["A. catch", "B. will catch", "C. will miss", "D. missed"]'::jsonb, 'C', 2, 'Unless 否條件 will miss。'),
('junior', 'By next week, she ___ the essay.', '["A. finishes", "B. will finish", "C. will have finished", "D. finished"]'::jsonb, 'B', 1, 'By + 未來完成。'),
('junior', 'I wish I ___ a bit taller.', '["A. am", "B. was", "C. were", "D. have been"]'::jsonb, 'C', 2, 'wish 與現在相反 were。'),
('junior', 'It''s time we ___ home.', '["A. go", "B. went", "C. gone", "D. going"]'::jsonb, 'B', 1, 'It''s time + 過去式建議 went。'),
('junior', 'I''d rather ___ at home tonight.', '["A. stay", "B. to stay", "C. stayed", "D. staying"]'::jsonb, 'C', 2, 'would rather + 原形。'),
('junior', 'He speaks as if he ___ everything.', '["A. know", "B. knew", "C. knows", "D. had known"]'::jsonb, 'A', 0, 'as if 非真 knew。'),
('junior', 'The documents ___ before Monday.', '["A. must submit", "B. must be submitted", "C. must submitting", "D. must submitted"]'::jsonb, 'B', 1, '被動 must be submitted。'),
('junior', 'The mistake ___ quickly.', '["A. corrected", "B. was corrected", "C. was correcting", "D. corrects"]'::jsonb, 'C', 2, '被改正 was corrected。'),
('junior', 'She denied ___ the email.', '["A. send", "B. sending", "C. to send", "D. sent"]'::jsonb, 'B', 1, 'deny + 動名詞。'),
('junior', 'He keeps ___ the same mistake.', '["A. make", "B. making", "C. to make", "D. made"]'::jsonb, 'A', 0, 'keep + 動名詞。'),
('junior', 'I''m considering ___ jobs.', '["A. change", "B. to change", "C. changing", "D. changed"]'::jsonb, 'C', 2, 'consider + 動名詞。'),
('junior', 'The test was ___ difficult that many failed.', '["A. so", "B. such", "C. very", "D. too"]'::jsonb, 'B', 1, 'so...that。'),
('junior', 'Scarcely had the train stopped ___ passengers rushed out.', '["A. than", "B. when", "C. before", "D. until"]'::jsonb, 'B', 1, 'Scarcely...when。'),
('junior', 'Were she here, she ___ agree.', '["A. will", "B. would", "C. can", "D. should"]'::jsonb, 'B', 1, '虛擬 would。'),
('junior', 'The athlete ___ ankle during practice.', '["A. sprains", "B. sprained", "C. was spraining", "D. has sprained"]'::jsonb, 'C', 2, '過去受傷 sprained。'),
('junior', 'The museum ___ at nine every day.', '["A. open", "B. opens", "C. is opened", "D. is opening"]'::jsonb, 'A', 0, '習慣 opens。'),
('junior', 'Neither the coach nor the players ___ ready.', '["A. was", "B. were", "C. is", "D. are"]'::jsonb, 'B', 1, '就近 players were。'),
('junior', 'The committee ___ divided on the issue.', '["A. is", "B. are", "C. was", "D. were"]'::jsonb, 'C', 2, '集合名詞視為複數 were。'),
('junior', 'So great ___ the noise that we covered our ears.', '["A. is", "B. was", "C. were", "D. be"]'::jsonb, 'B', 1, '倒裝 So great was。'),
('junior', 'Only after reading the manual ___ how it worked.', '["A. I understood", "B. did I understand", "C. I did understand", "D. understood I"]'::jsonb, 'C', 2, 'Only after 倒裝 did I。'),
('junior', 'Had I known, I ___ warned you.', '["A. will", "B. would", "C. would have", "D. had"]'::jsonb, 'B', 1, '與過去相反 would have。'),
('junior', 'She speaks French fluently; ___, she lived in Paris.', '["A. because", "B. for instance", "C. moreover", "D. although"]'::jsonb, 'C', 2, '舉例 for instance。'),
('junior', '___ the fog, the plane landed safely.', '["A. Because", "B. Despite", "C. Although", "D. Since"]'::jsonb, 'A', 0, '儘管 despite + 名詞。'),
('junior', 'He is used ___ long hours.', '["A. to work", "B. to working", "C. work", "D. working"]'::jsonb, 'B', 1, 'be used to + 動名詞。'),
('junior', 'The picture ___ from the wall.', '["A. fell", "B. fell down", "C. was fallen", "D. felled"]'::jsonb, 'C', 2, '自己落下 fell。'),
('junior', 'I can''t imagine ___ on Mars.', '["A. live", "B. to live", "C. living", "D. lived"]'::jsonb, 'B', 1, 'imagine + 動名詞。'),
('junior', 'She insisted ___ paying for dinner.', '["A. on", "B. in", "C. for", "D. to"]'::jsonb, 'A', 0, 'insist on + 動名詞。'),
('junior', 'They accused him ___ theft.', '["A. for", "B. of", "C. with", "D. about"]'::jsonb, 'C', 2, 'accuse of。'),
('junior', 'I''m allergic ___ peanuts.', '["A. for", "B. to", "C. of", "D. with"]'::jsonb, 'B', 1, 'allergic to。'),
('junior', 'The more you practice, ___ you will become.', '["A. more fluent", "B. the more fluent", "C. most fluent", "D. fluently"]'::jsonb, 'B', 1, 'the more...the more。'),
('junior', 'No sooner ___ the bell rung than the students left.', '["A. had", "B. did", "C. has", "D. was"]'::jsonb, 'A', 0, 'No sooner had + 過去分詞。'),
('junior', 'Little ___ that he was being filmed.', '["A. he realizes", "B. did he realize", "C. he realized", "D. does he realize"]'::jsonb, 'B', 1, 'Little 倒裝 did he realize。'),
('junior', 'Not only ___ the report, but she also presented it.', '["A. she wrote", "B. did she write", "C. she did write", "D. had she wrote"]'::jsonb, 'C', 2, 'Not only 倒裝 did she write。'),
('junior', 'If he ___ harder, he would have passed.', '["A. studies", "B. studied", "C. had studied", "D. has studied"]'::jsonb, 'B', 1, '與過去相反 had studied。'),
('junior', 'The contract ___ last Friday.', '["A. signs", "B. was signed", "C. signed", "D. is signing"]'::jsonb, 'C', 2, '被簽署 was signed。'),
('junior', 'She suggested ___ a taxi.', '["A. take", "B. taking", "C. to take", "D. took"]'::jsonb, 'A', 0, 'suggest + 動名詞。'),
('junior', 'I''d prefer ___ rather than walk.', '["A. drive", "B. to drive", "C. driving", "D. drove"]'::jsonb, 'B', 1, 'prefer to drive。'),
('junior', 'There''s no use ___ over spilt milk.', '["A. cry", "B. crying", "C. to cry", "D. cried"]'::jsonb, 'C', 2, 'no use + 動名詞。'),
('junior', 'He was seen ___ the building.', '["A. enter", "B. to enter", "C. entering", "D. entered"]'::jsonb, 'B', 1, 'be seen to enter。'),
('junior', 'The problem needs ___ soon.', '["A. solve", "B. solving", "C. to solve", "D. solved"]'::jsonb, 'A', 0, 'need + 動名詞。'),
('junior', 'She is capable ___ running a marathon.', '["A. for", "B. of", "C. in", "D. to"]'::jsonb, 'C', 2, 'capable of。'),
('junior', 'I''m fed up ___ waiting.', '["A. for", "B. with", "C. of", "D. at"]'::jsonb, 'B', 1, 'fed up with。'),
('junior', 'He confessed ___ the crime.', '["A. commit", "B. to committing", "C. committing", "D. committed"]'::jsonb, 'A', 0, 'confess to + 動名詞。'),
('junior', 'The storm having passed, we ___ outside.', '["A. go", "B. went", "C. could go", "D. going"]'::jsonb, 'C', 2, '獨立主格後 could go。'),
('junior', '___ tired, she went to bed early.', '["A. Be", "B. Being", "C. Been", "D. Is"]'::jsonb, 'B', 1, '分詞原因 Being tired。'),
('junior', 'Never have I ___ such a beautiful sunset.', '["A. see", "B. saw", "C. seen", "D. seeing"]'::jsonb, 'C', 2, 'Never have I + 過去分詞 seen。'),
('junior', 'The package ___ delivered yesterday.', '["A. is", "B. was", "C. has been", "D. had been"]'::jsonb, 'B', 1, '昨天被送 was delivered。'),
('junior', 'She can''t help ___ when she hears that song.', '["A. sing", "B. singing", "C. to sing", "D. sang"]'::jsonb, 'A', 0, 'can''t help + 動名詞。'),
('junior', 'He objected ___ treated unfairly.', '["A. to be", "B. to being", "C. being", "D. be"]'::jsonb, 'C', 2, 'object to being。'),
('junior', '___ opening the window?', '["A. Would you mind", "B. Do you mind", "C. You would mind", "D. Would mind you"]'::jsonb, 'B', 1, 'Would you mind + V-ing。'),
('junior', 'It is essential that he ___ on time.', '["A. is", "B. be", "C. will be", "D. being"]'::jsonb, 'C', 2, 'essential that + (should) be。'),
('junior', 'The new law will ___ next month.', '["A. effect", "B. take effect", "C. take effects", "D. make effect"]'::jsonb, 'B', 1, '生效 take effect。'),
('junior', 'She has worked here ___ 2018.', '["A. since", "B. for", "C. from", "D. in"]'::jsonb, 'A', 0, '起點 since 2018。'),
('junior', 'By the time we arrived, the film ___ .', '["A. starts", "B. started", "C. had started", "D. was starting"]'::jsonb, 'C', 2, '過去完成 had started。'),
('junior', 'He acted ___ nothing had happened.', '["A. as if", "B. even if", "C. although", "D. unless"]'::jsonb, 'B', 1, '好像 as if。'),
('junior', 'The children were playing while their parents ___ .', '["A. talk", "B. talked", "C. were talking", "D. had talked"]'::jsonb, 'C', 2, 'while 過去進行 were talking。'),
('junior', 'I ___ rather you didn''t smoke here.', '["A. would", "B. had", "C. should", "D. could"]'::jsonb, 'A', 0, 'would rather you didn''t。'),
('junior', 'Such ___ interesting book deserves praise.', '["A. a", "B. an", "C. the", "D. no article"]'::jsonb, 'B', 1, 'such an interesting book。'),
('junior', 'Hardly ___ sat down when the phone rang.', '["A. I had", "B. had I", "C. I did", "D. did I"]'::jsonb, 'B', 1, 'Hardly had I + 過去分詞。'),
('junior', 'The reason ___ he resigned is unclear.', '["A. which", "B. why", "C. what", "D. where"]'::jsonb, 'B', 1, 'reason why。'),
('junior', 'This is the town ___ I grew up.', '["A. which", "B. where", "C. that", "D. what"]'::jsonb, 'A', 0, '地點 where。'),
('junior', 'The man ___ car was stolen reported it.', '["A. who", "B. whom", "C. whose", "D. which"]'::jsonb, 'C', 2, '所有格 whose。'),
('junior', 'She didn''t know ___ to trust.', '["A. who", "B. whom", "C. whose", "D. which"]'::jsonb, 'B', 1, '誰 who to trust。'),
('junior', '___ wants to join should sign up.', '["A. Who", "B. Whoever", "C. Whomever", "D. Whatever"]'::jsonb, 'C', 2, '無論誰 Whoever。'),
('junior', 'However much he earns, he ___ saves nothing.', '["A. still", "B. yet", "C. ever", "D. never"]'::jsonb, 'B', 1, '讓步 However much。'),
('junior', 'The data ___ processed overnight.', '["A. was", "B. were", "C. is", "D. are"]'::jsonb, 'B', 1, '複數 data 在被動過去常用 were processed（美式亦可視為集合名詞用 was）。'),
('junior', 'Politics ___ a sensitive topic.', '["A. are", "B. is", "C. were", "D. be"]'::jsonb, 'A', 0, '抽象 politics 單數 is。'),
('junior', 'Each of the boys ___ a helmet.', '["A. have", "B. has", "C. having", "D. had"]'::jsonb, 'B', 1, 'each + 單數 has。'),
('junior', 'The furniture ___ delivered this morning.', '["A. were", "B. was", "C. are", "D. be"]'::jsonb, 'C', 2, 'furniture 不可數 was。'),
('junior', 'Rarely ___ such honesty.', '["A. you see", "B. do you see", "C. you saw", "D. have you seen"]'::jsonb, 'B', 1, 'Rarely 倒裝 do you see。'),
('junior', 'Not a single word ___ from him.', '["A. comes", "B. come", "C. came", "D. coming"]'::jsonb, 'A', 0, '否定主語單數 comes。'),
('junior', 'Should you need help, you ___ call us.', '["A. can", "B. could", "C. may", "D. might"]'::jsonb, 'C', 2, 'Should you... may call。'),
('junior', 'I ___ have locked the door — I''m not sure.', '["A. must", "B. might", "C. should", "D. would"]'::jsonb, 'B', 1, '不確定 might have。'),
('junior', 'The suspect ___ to have fled abroad.', '["A. believes", "B. is believed", "C. believed", "D. is believing"]'::jsonb, 'C', 2, 'is believed to。'),
('college', 'The hypothesis was ___ by subsequent experiments. (choose the best option).', '["A. refuted", "B. refuting", "C. refute", "D. to refute"]'::jsonb, 'A', 0, '被動語態，假設被後續實驗駁回。'),
('college', 'The study ___ a significant correlation between variables. (choose the best option).', '["A. established", "B. establishing", "C. establish", "D. to establish"]'::jsonb, 'A', 0, '過去研究「確立」相關，用過去式 established。'),
('college', 'The author''s argument is somewhat ___. (choose the best option).', '["A. tenuous", "B. tenuously", "C. tenuity", "D. tenuousness"]'::jsonb, 'A', 0, '形容詞作補語：論證略顯薄弱 tenuous。'),
('college', 'She gave a ___ account of the incident. (choose the best option).', '["A. dispassionate", "B. dispassionately", "C. dispassion", "D. dispassioning"]'::jsonb, 'A', 0, '名詞前用形容詞：客觀平實的敘述。'),
('college', 'The policy has had ___ effects on small businesses. (choose the best option).', '["A. deleterious", "B. deleteriously", "C. deleteriousness", "D. deleteriate"]'::jsonb, 'A', 0, '修飾名詞 effects 用形容詞 deleterious（有害）。'),
('college', 'Such behavior is ___ to the organization''s reputation. (choose the best option).', '["A. inimical", "B. inimically", "C. inimic", "D. inimicality"]'::jsonb, 'A', 0, 'be inimical to 表示對…有害。'),
('college', 'The results were ___ unexpected. (choose the best option).', '["A. wholly", "B. whole", "C. wholeness", "D. wholesome"]'::jsonb, 'A', 0, '修飾形容詞用副詞 wholly。'),
('college', 'The theory remains ___. (choose the best option).', '["A. contentious", "B. contentiously", "C. content", "D. contention"]'::jsonb, 'A', 0, 'remain + 形容詞：仍有爭議 contentious。'),
('college', 'The paper lacks ___ rigor. (choose the best option).', '["A. methodological", "B. methodologically", "C. methodology", "D. method"]'::jsonb, 'A', 0, '名詞前用形容詞 methodological。'),
('college', 'The evidence is ___. (choose the best option).', '["A. inconclusive", "B. inconclusively", "C. inconclude", "D. inconclusiveness"]'::jsonb, 'A', 0, '形容詞作補語：證據尚無定論。'),
('college', 'He drew an ___ between the two cases. (choose the best option).', '["A. analogy", "B. analogous", "C. analogously", "D. analog"]'::jsonb, 'A', 0, '不定冠詞後接名詞 analogy。'),
('college', 'The proposal was met with ___. (choose the best option).', '["A. skepticism", "B. skeptical", "C. skeptically", "D. skeptic"]'::jsonb, 'A', 0, '介詞後接名詞 skepticism。'),
('college', 'The finding ___ previous assumptions. (choose the best option).', '["A. contradicts", "B. contradict", "C. contradicting", "D. contradicted"]'::jsonb, 'A', 0, '主詞單數，現在式 contradicts。'),
('college', 'The variables were ___ controlled. (choose the best option).', '["A. carefully", "B. careful", "C. carefulness", "D. care"]'::jsonb, 'A', 0, '修飾過去分詞 controlled 用副詞。'),
('college', 'The essay ___ several seminal works. (choose the best option).', '["A. cites", "B. cite", "C. citing", "D. cited"]'::jsonb, 'A', 0, '現在簡單式或過去式；此處主詞第三人稱一般現在 cites。'),
('college', 'Scholars have long ___ this interpretation. (choose the best option).', '["A. disputed", "B. dispute", "C. disputing", "D. disputes"]'::jsonb, 'A', 0, '現在完成式 have disputed。'),
('college', 'The narrative ___ chronologically. (choose the best option).', '["A. unfolds", "B. unfold", "C. unfolding", "D. unfolded"]'::jsonb, 'A', 0, '主詞單數，敘述依時間展開 unfolds。'),
('college', 'The author ___ the reader''s expectations. (choose the best option).', '["A. subverts", "B. subvert", "C. subverting", "D. subverted"]'::jsonb, 'A', 0, '第三人稱現在式 subverts。'),
('college', 'The critique is ___ superficial. (choose the best option).', '["A. unduly", "B. undue", "C. undies", "D. undular"]'::jsonb, 'A', 0, '修飾形容詞 superficial 用副詞 unduly。'),
('college', 'The methodology is not ___ reproducible. (choose the best option).', '["A. readily", "B. ready", "C. readiness", "D. reading"]'::jsonb, 'A', 0, '修飾形容詞用副詞 readily。'),
('college', 'The speaker ___ her main points clearly. (choose the best option).', '["A. articulated", "B. articulate", "C. articulating", "D. articulates"]'::jsonb, 'A', 0, '過去演講用 articulated。'),
('college', 'The treaty ___ trade barriers. (choose the best option).', '["A. dismantled", "B. dismantle", "C. dismantling", "D. dismantles"]'::jsonb, 'A', 0, '過去事件 dismantled。'),
('college', 'Inflation has ___ consumer confidence. (choose the best option).', '["A. eroded", "B. erode", "C. eroding", "D. erodes"]'::jsonb, 'A', 0, '現在完成式 have eroded。'),
('college', 'The CEO ___ responsibility for the failure. (choose the best option).', '["A. accepted", "B. accepts", "C. accepting", "D. accept"]'::jsonb, 'A', 0, '過去接受責任 accepted。'),
('college', 'The committee''s decision is ___. (choose the best option).', '["A. binding", "B. bind", "C. bound", "D. binds"]'::jsonb, 'A', 0, '形容詞 binding 表示有約束力。'),
('college', 'The contract shall ___ on the first of July. (choose the best option).', '["A. take effect", "B. take effects", "C. take affecting", "D. take effective"]'::jsonb, 'A', 0, '固定用法 take effect 生效。'),
('college', 'The plaintiff ___ damages. (choose the best option).', '["A. sought", "B. seek", "C. seeking", "D. seeks"]'::jsonb, 'A', 0, '訴訟過去尋求賠償 sought。'),
('college', 'The court ___ the appeal. (choose the best option).', '["A. dismissed", "B. dismiss", "C. dismissing", "D. dismisses"]'::jsonb, 'A', 0, '過去駁回 dismissed。'),
('college', 'The statute is ___ to interpretation. (choose the best option).', '["A. subject", "B. subjective", "C. subjected", "D. subjecting"]'::jsonb, 'A', 0, 'be subject to 易於／須受…。'),
('college', 'Notwithstanding the risks, the board ___. (choose the best option).', '["A. proceeded", "B. proceed", "C. proceeding", "D. proceeds"]'::jsonb, 'A', 0, '儘管風險仍進行，過去 proceeded。'),
('college', 'The data ___ systematically biased. (choose the best option).', '["A. appear", "B. appears", "C. appearing", "D. appeared"]'::jsonb, 'A', 0, '將 data 當複數時動詞用 appear（亦有出版物視為單數而用 appears）。'),
('college', 'The phenomenon ___ further investigation. (choose the best option).', '["A. warrants", "B. warrant", "C. warranting", "D. warranted"]'::jsonb, 'A', 0, '現象「值得」進一步調查，第三人稱 warrants。'),
('college', 'The implications are far-___. (choose the best option).', '["A. reaching", "B. reached", "C. reach", "D. reaches"]'::jsonb, 'A', 0, '複合形容詞 far-reaching 深遠的。'),
('college', 'The argument ___ scrutiny. (choose the best option).', '["A. withstands", "B. withstand", "C. withstanding", "D. withstood"]'::jsonb, 'A', 0, '第三人稱現在 withstands。'),
('college', 'The sample size is ___. (choose the best option).', '["A. inadequate", "B. inadequately", "C. inadequacy", "D. inadequateness"]'::jsonb, 'A', 0, '形容詞補語 inadequate。'),
('college', 'The researchers ___ their conclusions cautiously. (choose the best option).', '["A. stated", "B. state", "C. stating", "D. states"]'::jsonb, 'A', 0, '過去陳述 stated。'),
('college', 'The model ___ reality only partially. (choose the best option).', '["A. reflects", "B. reflect", "C. reflecting", "D. reflected"]'::jsonb, 'A', 0, '現在式 reflects。'),
('college', 'The trend has ___ since 2020. (choose the best option).', '["A. accelerated", "B. accelerate", "C. accelerating", "D. accelerates"]'::jsonb, 'A', 0, '現在完成式 has accelerated。'),
('college', 'The article ___ plagiarism in the draft. (choose the best option).', '["A. alleged", "B. alleges", "C. allege", "D. alleging"]'::jsonb, 'A', 0, '過去報導 alleged。'),
('college', 'Prior ___ the meeting, circulate the agenda. (choose the best option).', '["A. to", "B. than", "C. of", "D. for"]'::jsonb, 'A', 0, 'prior to 相當於 before。'),
('college', 'The ethics board rarely ___ approval without review. (choose the best option).', '["A. withholds", "B. withhold", "C. withheld", "D. withholding"]'::jsonb, 'A', 0, '描述慣例用現在式 withholds。'),
('college', 'The manuscript was ___ peer review. (choose the best option).', '["A. subjected to", "B. subject to", "C. subjecting to", "D. subjective to"]'::jsonb, 'A', 0, 'be subjected to 遭受到…審查。'),
('college', 'The speaker ___ an anecdote to illustrate the point. (choose the best option).', '["A. invoked", "B. invoke", "C. invoking", "D. invokes"]'::jsonb, 'A', 0, '過去演講援引 invoked。'),
('college', 'The framework is ___ applicable across disciplines. (choose the best option).', '["A. broadly", "B. broad", "C. broaden", "D. breadth"]'::jsonb, 'A', 0, '修飾形容詞 applicable 用副詞 broadly。'),
('college', 'The decline was ___ precipitous. (choose the best option).', '["A. somewhat", "B. somewhatly", "C. some", "D. something"]'::jsonb, 'A', 0, '修飾形容詞 precipitous 用副詞 somewhat。'),
('college', 'The author ___ the limitations of the study. (choose the best option).', '["A. acknowledges", "B. acknowledge", "C. acknowledging", "D. acknowledged"]'::jsonb, 'D', 3, '過去式 acknowledged 或現在 acknowledges；此處選 acknowledged 表文中承認。'),
('college', 'The policy ___ unintended consequences. (choose the best option).', '["A. entailed", "B. entail", "C. entailing", "D. entails"]'::jsonb, 'A', 0, '過去造成 entailed。'),
('college', 'The dataset was ___ anonymized. (choose the best option).', '["A. properly", "B. proper", "C. prop", "D. propriety"]'::jsonb, 'A', 0, '修飾過去分詞用副詞 properly。'),
('college', 'The reviewer questioned the paper''s ___. (choose the best option).', '["A. coherence", "B. coherent", "C. coherently", "D. cohere"]'::jsonb, 'A', 0, '所有格後接名詞 coherence。'),
('college', 'The conclusion does not ___ follow from the premises. (choose the best option).', '["A. necessarily", "B. necessary", "C. necessity", "D. necessitate"]'::jsonb, 'A', 0, '修飾動詞 follow 用副詞 necessarily。'),
('college', 'The theory was ___ received by peers. (choose the best option).', '["A. well", "B. good", "C. best", "D. better"]'::jsonb, 'A', 0, '修飾過去分詞 received 用副詞 well。'),
('college', 'The grant ___ interdisciplinary collaboration. (choose the best option).', '["A. fostered", "B. foster", "C. fostering", "D. fosters"]'::jsonb, 'A', 0, '過去促進 fostered。'),
('college', 'The lecture ___ key terminology. (choose the best option).', '["A. clarified", "B. clarify", "C. clarifying", "D. clarifies"]'::jsonb, 'A', 0, '過去闡明 clarified。'),
('college', 'The experiment ___ a controlled environment. (choose the best option).', '["A. used", "B. use", "C. using", "D. uses"]'::jsonb, 'A', 0, '過去使用 used。'),
('college', 'Participants were ___ at random. (choose the best option).', '["A. assigned", "B. assign", "C. assigning", "D. assigns"]'::jsonb, 'A', 0, '過去分詞被指派 assigned。'),
('college', 'The survey ___ self-reported bias. (choose the best option).', '["A. exhibits", "B. exhibit", "C. exhibiting", "D. exhibited"]'::jsonb, 'D', 3, '過去顯示 exhibited 或現在 exhibits；選 exhibited 表調查當時。'),
('college', 'The algorithm ___ faster convergence. (choose the best option).', '["A. enabled", "B. enable", "C. enabling", "D. enables"]'::jsonb, 'A', 0, '過去使可能 enabled。'),
('college', 'The chapter ___ the historical context. (choose the best option).', '["A. sketches", "B. sketch", "C. sketching", "D. sketched"]'::jsonb, 'D', 3, '過去概述 sketched。'),
('college', 'The index ___ several omissions. (choose the best option).', '["A. contains", "B. contain", "C. containing", "D. contained"]'::jsonb, 'D', 3, '過去包含 contained。'),
('college', 'The keynote ___ the conference theme. (choose the best option).', '["A. addressed", "B. address", "C. addressing", "D. addresses"]'::jsonb, 'A', 0, '過去呼應 addressed。'),
('college', 'The panel ___ for three hours. (choose the best option).', '["A. lasted", "B. last", "C. lasting", "D. lasts"]'::jsonb, 'A', 0, '過去持續 lasted。'),
('college', 'The editor ___ the manuscript for clarity. (choose the best option).', '["A. tightened", "B. tighten", "C. tightening", "D. tightens"]'::jsonb, 'A', 0, '過去修訂 tightened。'),
('college', 'The grant proposal was ___. (choose the best option).', '["A. rejected", "B. reject", "C. rejecting", "D. rejects"]'::jsonb, 'A', 0, '被動過去分詞 rejected。'),
('college', 'The university ___ new admissions criteria. (choose the best option).', '["A. adopted", "B. adopt", "C. adopting", "D. adopts"]'::jsonb, 'A', 0, '過去採納 adopted。'),
('college', 'The lecture hall was ___ full. (choose the best option).', '["A. nearly", "B. near", "C. nearest", "D. nearer"]'::jsonb, 'A', 0, '修飾形容詞 full 用副詞 nearly。'),
('college', 'The article ___ a literature review. (choose the best option).', '["A. includes", "B. include", "C. including", "D. included"]'::jsonb, 'D', 3, '過去包含 included。'),
('college', 'The seminar ___ graduate students only. (choose the best option).', '["A. targeted", "B. target", "C. targeting", "D. targets"]'::jsonb, 'A', 0, '過去以…為對象 targeted。'),
('college', 'The findings need to be ___ in a larger sample. (choose the best option).', '["A. replicated", "B. replicate", "C. replicating", "D. replicates"]'::jsonb, 'A', 0, '研究須在更大樣本中「重複驗證」。'),
('college', 'The paper ___ ethical approval before data collection. (choose the best option).', '["A. obtained", "B. obtain", "C. obtaining", "D. obtains"]'::jsonb, 'A', 0, '過去取得倫理核准 obtained。'),
('college', 'The authors ___ any conflicts of interest. (choose the best option).', '["A. disclosed", "B. disclose", "C. disclosing", "D. discloses"]'::jsonb, 'A', 0, '過去揭露利益衝突 disclosed。'),
('college', 'The discussion section ___ the results to theory. (choose the best option).', '["A. relates", "B. relate", "C. relating", "D. related"]'::jsonb, 'D', 3, '過去將結果連結理論 related。'),
('college', 'Table 2 ___ descriptive statistics for each group. (choose the best option).', '["A. summarizes", "B. summarize", "C. summarizing", "D. summarized"]'::jsonb, 'D', 3, '過去式 summarized 表列出／總述。'),
('college', 'The limitation ___ the cross-sectional design. (choose the best option).', '["A. concerns", "B. concern", "C. concerning", "D. concerned"]'::jsonb, 'A', 0, '描述研究限制常用現在式 concerns，表示『此限制在於／涉及…』。'),
('college', 'Future research should ___ longitudinal methods. (choose the best option).', '["A. employ", "B. employs", "C. employing", "D. employed"]'::jsonb, 'A', 0, '情態動詞後接原形 employ。'),
('college', 'The coefficient was statistically ___ at p < .05. (choose the best option).', '["A. significant", "B. significantly", "C. significance", "D. signify"]'::jsonb, 'A', 0, '形容詞補語 significant 表示達顯著水準。'),
('professor', 'The term ''morpheme'' refers to ___. (choose the best option).', '["A. a minimal meaningful unit", "B. a speech sound", "C. a dialect variant", "D. a writing system"]'::jsonb, 'A', 0, '語言學中 morpheme 為最小有意義單位。'),
('professor', 'A phoneme is best described as ___. (choose the best option).', '["A. a letter of the alphabet", "B. a contrastive sound category", "C. a syllable", "D. a stress pattern"]'::jsonb, 'B', 1, '音位是具區別意義功能的音類別。'),
('professor', 'In linguistics, ''syntax'' concerns ___. (choose the best option).', '["A. word meanings", "B. sentence structure", "C. sound patterns", "D. language history"]'::jsonb, 'B', 1, '句法研究句子結構。'),
('professor', 'Semantics primarily deals with ___. (choose the best option).', '["A. pronunciation", "B. meaning", "C. spelling reform", "D. orthography"]'::jsonb, 'B', 1, '語義學研究意義。'),
('professor', 'Pragmatics focuses on ___. (choose the best option).', '["A. sentence length", "B. language use in context", "C. phonetic transcription", "D. etymology"]'::jsonb, 'B', 1, '語用學關注語境中的使用。'),
('professor', 'An example of a polyseme is ''bank'' meaning river edge and financial institution; this illustrates ___. (choose the best option).', '["A. homophony", "B. polysemy", "C. synonymy", "D. antonymy"]'::jsonb, 'B', 1, '同一詞形多義為 polysemy。'),
('professor', 'If two words sound identical but differ in meaning and spelling, they are ___. (choose the best option).', '["A. synonyms", "B. homophones", "C. hypernyms", "D. collocations"]'::jsonb, 'B', 1, '同音異義為 homophones。'),
('professor', 'The study of word origins is ___. (choose the best option).', '["A. syntax", "B. phonology", "C. etymology", "D. morphology"]'::jsonb, 'C', 2, '詞源研究為 etymology。'),
('professor', 'In English, ''unhappiness'' contains ___. (choose the best option).', '["A. one morpheme", "B. two morphemes", "C. three morphemes", "D. four morphemes"]'::jsonb, 'C', 2, 'un + happy + ness 三個詞素。'),
('professor', 'Which pair illustrates phonemic contrast (minimal pairs) (choose the best option)?', '["A. pin vs spin /p/", "B. pit vs bit /p/-/b/", "C. cat vs cats /s/-/z/", "D. ship vs sheep"]'::jsonb, 'B', 1, 'pit / bit 僅差一個音位 /p/ 與 /b/，為最小對立組，顯示音位對立。'),
('professor', 'A prescriptive rule tells speakers ___. (choose the best option).', '["A. how language is actually used", "B. how they ought to use language", "C. how babies acquire language", "D. how dialects spread"]'::jsonb, 'B', 1, '規範語法規定「應如何」使用。'),
('professor', 'Descriptive linguistics aims to ___. (choose the best option).', '["A. rank languages", "B. describe actual usage", "C. ban loanwords", "D. fix spelling"]'::jsonb, 'B', 1, '描寫語言學描述實際用法。'),
('professor', 'The sapir-whorf hypothesis concerns ___. (choose the best option).', '["A. sound symbolism", "B. language and thought", "C. language families", "D. writing direction"]'::jsonb, 'B', 1, '薩丕爾—沃夫假設探討語言與思維。'),
('professor', 'Metonymy is exemplified by ___. (choose the best option).', '["A. ''kick the bucket''", "B. The crown announced...", "C. It''s raining cats and dogs", "D. Time flies"]'::jsonb, 'B', 1, 'The crown 借代王室為 metonymy。'),
('professor', 'A mixed metaphor is problematic because it ___. (choose the best option).', '["A. uses passive voice", "B. combines clashing images", "C. is too short", "D. lacks a thesis"]'::jsonb, 'B', 1, '混合隱喻意象衝突。'),
('professor', 'Zeugma joins ___. (choose the best option).', '["A. two unrelated metaphors", "B. one word with two objects in different senses", "C. two synonyms", "D. subject and object"]'::jsonb, 'B', 1, '軛式搭配一詞配兩受詞不同義。'),
('professor', 'Chiasmus involves ___. (choose the best option).', '["A. rhyme", "B. reversed grammatical structure", "C. alliteration", "D. omission of vowels"]'::jsonb, 'B', 1, '交錯配列為結構倒序對照。'),
('professor', 'Asyndeton omits ___. (choose the best option).', '["A. verbs", "B. subjects", "C. conjunctions", "D. articles"]'::jsonb, 'C', 2, '連珠式省略連接詞。'),
('professor', 'Polysyndeton repeats ___. (choose the best option).', '["A. subjects", "B. conjunctions", "C. prepositions", "D. articles"]'::jsonb, 'B', 1, '連綴式重複連接詞。'),
('professor', 'Anaphora is ___. (choose the best option).', '["A. end rhyme", "B. repetition at the start of successive clauses", "C. use of foreign words", "D. inversion only"]'::jsonb, 'B', 1, '首語重複為句首重複。'),
('professor', 'Catachresis refers to ___. (choose the best option).', '["A. correct grammar", "B. strained or improper metaphor", "C. metrical feet", "D. IPA notation"]'::jsonb, 'B', 1, '誤喻為不當或過度延伸隱喻。'),
('professor', 'Synecdoche uses ___. (choose the best option).', '["A. rhyme", "B. a part for the whole or vice versa", "C. homophones", "D. palindrome"]'::jsonb, 'B', 1, '提喻以部分代整體或反之。'),
('professor', 'Litotes expresses affirmation through ___. (choose the best option).', '["A. hyperbole", "B. double negation or understatement", "C. simile", "D. allusion"]'::jsonb, 'B', 1, '曲言法以否定或輕描淡寫表肯定。'),
('professor', 'Pejorative connotation means the word feels ___. (choose the best option).', '["A. neutral", "B. positive", "C. negative", "D. technical"]'::jsonb, 'C', 2, '貶義為負面色彩。'),
('professor', 'If an argument affirms the consequent, it is ___. (choose the best option).', '["A. valid", "B. sound", "C. formally invalid", "D. inductive only"]'::jsonb, 'C', 2, '肯定後件為形式謬誤。'),
('professor', 'Denying the antecedent is ___. (choose the best option).', '["A. always valid", "B. formally invalid", "C. the same as modus ponens", "D. a strong analogy"]'::jsonb, 'B', 1, '否定前件為無效推論。'),
('professor', 'A deductively valid argument can still be ___. (choose the best option).', '["A. unsound if premises are false", "B. always sound", "C. inductive", "D. self-refuting always"]'::jsonb, 'A', 0, '有效論證若前提假仍可 unsound。'),
('professor', 'An ad hoc rescue revises a theory ___. (choose the best option).', '["A. before testing", "B. only to protect it from falsification", "C. using statistics only", "D. through translation"]'::jsonb, 'B', 1, '特設性防衛為免於被否證而補救。'),
('professor', 'Straw man fallacy involves ___. (choose the best option).', '["A. using analogies", "B. misrepresenting an opponent''s view", "C. appealing to pity", "D. equivocation only"]'::jsonb, 'B', 1, '稻草人謬誤扭曲對方論點。'),
('professor', 'Equivocation shifts ___. (choose the best option).', '["A. tenses", "B. the meaning of a key term", "C. font size", "D. sample size"]'::jsonb, 'B', 1, '歧義謬誤偷換關鍵詞義。'),
('professor', 'Post hoc ergo propter hoc mistakes ___. (choose the best option).', '["A. correlation for authentication", "B. sequence for causation", "C. cause for correlation", "D. definition for example"]'::jsonb, 'B', 1, '後此謬誤把先後當因果。'),
('professor', 'Begging the question ___. (choose the best option).', '["A. asks politely", "B. assumes the conclusion in premises", "C. uses only empirical data", "D. avoids pronouns"]'::jsonb, 'B', 1, '循環論證把結論藏於前提。'),
('professor', 'The word ''otiose'' most nearly means ___. (choose the best option).', '["A. meticulous", "B. superfluous", "C. rapid", "D. fragrant"]'::jsonb, 'B', 1, 'otiose 意為多餘、無用。'),
('professor', 'The word ''perspicacious'' suggests ___. (choose the best option).', '["A. sloppy thinking", "B. keen insight", "C. physical strength", "D. anger"]'::jsonb, 'B', 1, 'perspicacious 表示敏銳洞察。'),
('professor', 'The word ''recalcitrant'' fits ___. (choose the best option).', '["A. a willing volunteer", "B. a stubborn resistor", "C. a transparent liquid", "D. a cheap fabric"]'::jsonb, 'B', 1, 'recalcitrant 形容頑抗不服。'),
('professor', 'The word ''sycophant'' denotes ___. (choose the best option).', '["A. a wise teacher", "B. a servile flatterer", "C. a neutral judge", "D. a brave pioneer"]'::jsonb, 'B', 1, 'sycophant 為阿諛奉承者。'),
('professor', 'The word ''laconic'' describes speech that is ___. (choose the best option).', '["A. lengthy", "B. brief", "C. loud", "D. archaic"]'::jsonb, 'B', 1, 'laconic 表示簡潔寡言。'),
('professor', 'The idiom ''to pull someone''s leg'' means ___. (choose the best option).', '["A. to help them walk", "B. to tease or joke", "C. to betray them", "D. to lend money"]'::jsonb, 'B', 1, '英式幽默表示開玩笑、捉弄。'),
('professor', 'The idiom ''bury the hatchet'' means ___. (choose the best option).', '["A. hide tools", "B. make peace", "C. start a fight", "D. plant trees"]'::jsonb, 'B', 1, '言歸於好、止息爭端。'),
('professor', 'The idiom ''let sleeping dogs lie'' advises ___. (choose the best option).', '["A. wake pets", "B. avoid stirring up trouble", "C. train animals", "D. sleep more"]'::jsonb, 'B', 1, '勿挑起不必要的麻煩。'),
('professor', 'The idiom ''the ball is in your court'' means ___. (choose the best option).', '["A. play tennis", "B. it''s your turn to act", "C. you lost", "D. the game ended"]'::jsonb, 'B', 1, '輪到你採取行動。'),
('professor', 'The idiom ''cut corners'' suggests ___. (choose the best option).', '["A. meticulous work", "B. doing something hastily or improperly", "C. taking a shortcut road only", "D. building squares"]'::jsonb, 'B', 1, '偷工減料、走捷徑敷衍。'),
('professor', 'An oxymoron pairs ___. (choose the best option).', '["A. synonyms", "B. contradictory terms", "C. foreign words", "D. rhyming words"]'::jsonb, 'B', 1, '矛盾修辭並置相反概念。'),
('professor', 'Epistemic modality expresses ___. (choose the best option).', '["A. obligation about the past", "B. speaker''s degree of commitment to truth", "C. physical ability only", "D. future tense only"]'::jsonb, 'B', 1, '認識情態表說話者對命題真假的確信度。'),
('professor', 'Deictic expressions depend on ___. (choose the best option).', '["A. Latin roots", "B. utterance context", "C. metrical stress", "D. silent letters"]'::jsonb, 'B', 1, '指示詞依賴語境座標。'),
('professor', 'A minimal pair in phonology demonstrates ___. (choose the best option).', '["A. free variation", "B. phonemic contrast", "C. allophony only", "D. tone sandhi"]'::jsonb, 'B', 1, '最小對立組顯示音位對立。'),
('professor', 'Complementary distribution typically indicates ___. (choose the best option).', '["A. phonemes", "B. allophones of one phoneme", "C. minimal pairs", "D. word stress"]'::jsonb, 'B', 1, '互補分布多為同一音位之變體。'),
('professor', 'The passive voice is sometimes preferred in scientific writing to ___. (choose the best option).', '["A. increase wordiness", "B. foreground the process or result", "C. avoid verbs", "D. hide subject always"]'::jsonb, 'B', 1, '被動可突出過程或結果。'),
('professor', 'The rhetorical question primarily functions to ___. (choose the best option).', '["A. request information only", "B. prompt reflection rather than an answer", "C. change tense", "D. translate literally"]'::jsonb, 'B', 1, '反問用於引發思考而非真問。'),
('professor', 'Pathos appeals to ___. (choose the best option).', '["A. logic", "B. credibility", "C. emotion", "D. grammar"]'::jsonb, 'C', 2, '悲情訴諸情感 pathos。'),
('professor', 'Logos appeals to ___. (choose the best option).', '["A. emotion", "B. character", "C. reasoning and evidence", "D. rhythm"]'::jsonb, 'C', 2, '理性訴諸論證 logos。'),
('professor', 'Ethos appeals to ___. (choose the best option).', '["A. statistics only", "B. speaker credibility", "C. musicality", "D. imagery only"]'::jsonb, 'B', 1, '人格訴諸可信度 ethos。'),
('professor', 'Ambiguity of scope may confuse whether ___. (choose the best option).', '["A. a verb is transitive", "B. negation applies to one clause or another", "C. nouns are plural", "D. letters are silent"]'::jsonb, 'B', 1, '範域歧義影響否定範圍。'),
('professor', 'Vagueness differs from ambiguity because vagueness ___. (choose the best option).', '["A. has two precise senses", "B. involves borderline cases", "C. is always grammatical", "D. requires synonyms"]'::jsonb, 'B', 1, '模糊涉及界線案例而非雙義。'),
('professor', 'Performative utterances ___. (choose the best option).', '["A. cannot be spoken", "B. do something by being said", "C. only describe weather", "D. lack verbs"]'::jsonb, 'B', 1, '施為句以說出即完成行為。'),
('professor', 'Implicature (Gricean) relies on ___. (choose the best option).', '["A. literal grammar only", "B. conversational cooperation and context", "C. spelling rules", "D. IPA charts"]'::jsonb, 'B', 1, '含意依合作原則與語境推導。'),
('professor', 'A malapropism is ___. (choose the best option).', '["A. a deliberate pun", "B. an amusing word substitution error", "C. a silent letter", "D. a dialect map"]'::jsonb, 'B', 1, '誤用近似音詞造成滑稽效果。'),
('professor', 'Proprioceptive imagery appeals to ___. (choose the best option).', '["A. sight", "B. internal bodily sensation", "C. hearing", "D. taste only"]'::jsonb, 'B', 1, '本體感覺意象描寫身體內部感覺。'),
('professor', 'Synesthesia in literature ___. (choose the best option).', '["A. avoids metaphor", "B. crosses sensory domains", "C. uses only facts", "D. removes adjectives"]'::jsonb, 'B', 1, '通感跨感官域。'),
('professor', 'The hedging phrase ''I might be wrong, but...'' serves to ___. (choose the best option).', '["A. assert certainty", "B. soften the claim", "C. change topic", "D. quote sources"]'::jsonb, 'B', 1, '模糊限制語弱化斷言。'),
('professor', 'Parallelism in prose primarily enhances ___. (choose the best option).', '["A. confusion", "B. rhythm and clarity", "C. spelling", "D. font choice"]'::jsonb, 'B', 1, '排比增節奏與清晰度。'),
('professor', 'Antimetabole repeats words in ___. (choose the best option).', '["A. random order", "B. reverse order", "C. alphabetical order", "D. silent letters"]'::jsonb, 'B', 1, '逆序重複為 antimetabole。'),
('professor', 'The pathetic fallacy attributes human emotion to ___. (choose the best option).', '["A. numbers", "B. nature or objects", "C. verbs only", "D. footnotes"]'::jsonb, 'B', 1, '感情誤置賦予自然或物情感。'),
('professor', 'An enthymeme in rhetoric is ___. (choose the best option).', '["A. a long poem", "B. a syllogism with an unstated premise", "C. a type of irony", "D. a grammar rule"]'::jsonb, 'B', 1, '省略三段論省略前提。'),
('professor', 'The distinction between ''fewer'' and ''less'' is prescriptively about ___. (choose the best option).', '["A. formality", "B. count vs mass nouns", "C. British vs American", "D. past vs present"]'::jsonb, 'B', 1, '規範上 fewer 配可數、less 配不可數。'),
('professor', 'In philosophy of language, ''extension'' of a term is ___. (choose the best option).', '["A. its intension", "B. the set of things it denotes", "C. its etymology", "D. its pronunciation"]'::jsonb, 'B', 1, '外延為詞所指對象集合。'),
('professor', 'The intension of a word includes ___. (choose the best option).', '["A. only pronunciation", "B. associative or definitional properties", "C. only spelling", "D. rhyme scheme"]'::jsonb, 'B', 1, '內涵為定義性質與屬性。'),
('professor', 'If P implies Q, then ''not Q'' implies ___. (choose the best option).', '["A. P", "B. not P", "C. Q", "D. P and Q"]'::jsonb, 'B', 1, '拒取式：非 Q 則非 P（假設原為 P→Q）。'),
('professor', 'A contingent truth is one that ___. (choose the best option).', '["A. must be true in all worlds", "B. could have been otherwise", "C. is self-contradictory", "D. only concerns math"]'::jsonb, 'B', 1, '偶然真理可以不是如此。'),
('professor', 'Analytic statements are often characterized as ___. (choose the best option).', '["A. empirical", "B. true by virtue of meaning", "C. always false", "D. poetic"]'::jsonb, 'B', 1, '分析句依意義為真。'),
('professor', 'Synthetic statements ___. (choose the best option).', '["A. are true by definition only", "B. combine concepts not contained in the subject", "C. cannot be false", "D. lack predicates"]'::jsonb, 'B', 1, '綜合句把主詞所無之概念連結起來。'),
('professor', 'The fallacy of composition assumes ___. (choose the best option).', '["A. parts equal whole properties", "B. what is true of parts is true of the whole", "C. correlation implies causation", "D. experts are wrong"]'::jsonb, 'B', 1, '合成謬誤以部分性質推整體。'),
('professor', 'The fallacy of division assumes ___. (choose the best option).', '["A. the whole''s property belongs to every part", "B. correlation is causation", "C. samples are random", "D. definitions shift"]'::jsonb, 'A', 0, '分割謬誤以整體屬性推每一部分。'),
('professor', 'A virtue of a clear operational definition is that it ___. (choose the best option).', '["A. avoids all measurement", "B. makes variables observable and testable", "C. removes ethics", "D. eliminates theory"]'::jsonb, 'B', 1, '操作型定義使變項可觀測檢驗。'),
('professor', 'In academic hedging, the verb suggests is weaker than ___. (choose the best option).', '["A. might", "B. proves", "C. could", "D. may"]'::jsonb, 'B', 1, 'suggests 比 proves 語氣弱。');
