-- 300 rows · batch4 — regenerate: python3 supabase/generate_questions_300_batch4.py > supabase/questions_seed_300_batch4.sql

INSERT INTO questions (difficulty, question_text, options, correct_answer_old, correct_index, explanation) VALUES
('elementary', 'My mother and father ___ teachers.', '["A. am", "B. is", "C. are", "D. be"]'::jsonb, 'C', 2, '複數主詞 parents 用 are。'),
('elementary', 'My grandfather ___ reading every morning.', '["A. am", "B. is", "C. are", "D. be"]'::jsonb, 'B', 1, '第三人稱單數用 is。'),
('elementary', '___ there any milk left (choose the best option)?', '["A. Is", "B. Are", "C. Am", "D. Do"]'::jsonb, 'A', 0, '不可數 milk 與 there be 搭配用 Is there。'),
('elementary', '___ those your stickers (choose the best option)?', '["A. Is", "B. Are", "C. Am", "D. Was"]'::jsonb, 'B', 1, 'those 複數用 Are。'),
('elementary', 'I ___ not hungry. (choose the best option).', '["A. am", "B. is", "C. are", "D. be"]'::jsonb, 'A', 0, 'I 配 am。'),
('elementary', 'We ___ from Canada. (choose the best option).', '["A. am", "B. is", "C. are", "D. be"]'::jsonb, 'C', 2, 'We 複數用 are。'),
('elementary', '___ does the shop open (choose the best option)?', '["A. When", "B. Who", "C. Whose", "D. Which"]'::jsonb, 'A', 0, '問時間用 When。'),
('elementary', '___ bag are you carrying (choose the best option)?', '["A. Who", "B. Which", "C. Whose", "D. Where"]'::jsonb, 'B', 1, '問哪一個／款式用 Which。'),
('elementary', 'Every weekend she ___ her grandma. (choose the best option).', '["A. visit", "B. visits", "C. visiting", "D. visited"]'::jsonb, 'B', 1, '習慣動作 she + visit + s。'),
('elementary', 'They ___ football right now.', '["A. play", "B. plays", "C. are playing", "D. played"]'::jsonb, 'C', 2, 'now 表現在進行。'),
('elementary', 'Look! It ___ . (choose the best option).', '["A. rain", "B. rains", "C. is raining", "D. rained"]'::jsonb, 'C', 2, 'Look 提示正在發生。'),
('elementary', 'I ___ never ___ sushi. (choose the best option).', '["A. have / eat", "B. have / eaten", "C. has / eaten", "D. had / eat"]'::jsonb, 'B', 1, '現在完成式 have eaten。'),
('elementary', 'She ___ to Tokyo twice. (choose the best option).', '["A. go", "B. goes", "C. has gone", "D. went"]'::jsonb, 'C', 2, '經驗次數用現在完成式。'),
('elementary', 'Before bed I always ___ my teeth. (choose the best option).', '["A. brush", "B. brushes", "C. brushing", "D. brushed"]'::jsonb, 'A', 0, 'I + always + 現在式 brush。'),
('elementary', 'Can we ___ outside (choose the best option)?', '["A. plays", "B. play", "C. playing", "D. played"]'::jsonb, 'B', 1, 'can 後接原形。'),
('elementary', 'She ___ play the piano when she was six. (choose the best option).', '["A. can", "B. could", "C. may", "D. must"]'::jsonb, 'B', 1, '過去能力用 could。'),
('elementary', 'You ___ wear a helmet on this ride. (choose the best option).', '["A. should", "B. shouldn''t", "C. might", "D. could"]'::jsonb, 'A', 0, '安全規定建議 should。'),
('elementary', 'It is dark. You ___ leave alone.', '["A. should", "B. shouldn''t", "C. must", "D. might"]'::jsonb, 'B', 1, '危險情境建議不要.shouldn''t。'),
('elementary', 'There ___ many kinds of juice in the jug. (choose the best option).', '["A. is", "B. are", "C. be", "D. am"]'::jsonb, 'B', 1, 'kinds 為可數複數，用 there are。'),
('elementary', 'How ___ students are in the club (choose the best option)?', '["A. much", "B. many", "C. long", "D. often"]'::jsonb, 'B', 1, '可數名詞數量用 How many。'),
('elementary', 'How ___ does the ticket cost (choose the best option)?', '["A. many", "B. much", "C. often", "D. far"]'::jsonb, 'B', 1, '價錢用 How much。'),
('elementary', 'I would like ___ water, please.', '["A. any", "B. some", "C. many", "D. few"]'::jsonb, 'B', 1, '肯定請求液體用 some。'),
('elementary', 'We don''t have ___ eggs. (choose the best option).', '["A. some", "B. any", "C. much", "D. many"]'::jsonb, 'B', 1, '否定句「任何」用 any。'),
('elementary', 'That is ___ elephant. (choose the best option).', '["A. a", "B. an", "C. the", "D. no article"]'::jsonb, 'B', 1, 'elephant 母音開頭用 an。'),
('elementary', 'Pass me ___ salt. (choose the best option).', '["A. a", "B. an", "C. the", "D. no article"]'::jsonb, 'C', 2, '特指桌上的鹽用 the。'),
('elementary', '___ Earth goes around the Sun. (choose the best option).', '["A. A", "B. An", "C. The", "D. no article"]'::jsonb, 'C', 2, '獨一無二事物用 the。'),
('elementary', 'I''ve lost ___ pen you lent me. (choose the best option).', '["A. a", "B. an", "C. the", "D. no article"]'::jsonb, 'C', 2, '特定那支筆用 the。'),
('elementary', 'She runs ___ than her brother. (choose the best option).', '["A. fast", "B. faster", "C. fastest", "D. more fast"]'::jsonb, 'B', 1, '兩者比較用比較級 faster。'),
('elementary', 'This is the ___ pizza I''ve ever had. (choose the best option).', '["A. good", "B. better", "C. best", "D. more good"]'::jsonb, 'C', 2, 'ever 搭配最高級 best。'),
('elementary', 'My room is ___ than yours. (choose the best option).', '["A. big", "B. bigger", "C. biggest", "D. more big"]'::jsonb, 'B', 1, 'than 用比較級 bigger。'),
('elementary', 'She speaks English ___ . (choose the best option).', '["A. good", "B. well", "C. better", "D. best"]'::jsonb, 'B', 1, '修飾動詞 speak 用副詞 well。'),
('elementary', '___ carefully, please! (choose the best option).', '["A. Listen", "B. Listen to", "C. Hear", "D. Sound"]'::jsonb, 'A', 0, '祈使「聽」用 Listen（不及物）。'),
('elementary', '___ you help me carry this (choose the best option)?', '["A. Can", "B. Should", "C. Must", "D. May"]'::jsonb, 'A', 0, '請求協助常用 Can。'),
('elementary', 'I am interested ___ science fiction.', '["A. on", "B. in", "C. at", "D. for"]'::jsonb, 'B', 1, 'be interested in。'),
('elementary', 'Good ___! You''ll do better next time. (choose the best option).', '["A. luck", "B. luckily", "C. lucky", "D. unlucky"]'::jsonb, 'A', 0, '安慰常用 Good luck 或加油語境。'),
('elementary', 'See you ___ weekend! (choose the best option).', '["A. this", "B. at this", "C. on this", "D. the"]'::jsonb, 'A', 0, 'this weekend 固定說法。'),
('elementary', '___ happy birthday! (choose the best option).', '["A. Say", "B. Wish", "C. Tell", "D. Speak"]'::jsonb, 'B', 1, '祝賀生日常用 Wish。'),
('elementary', 'Turn ___ the TV; it''s too loud. (choose the best option).', '["A. on", "B. off", "C. up", "D. in"]'::jsonb, 'B', 1, '太吵要關掉用 turn off。'),
('elementary', '___ up early makes me tired. (choose the best option).', '["A. Wake", "B. Waking", "C. Woke", "D. Wakes"]'::jsonb, 'B', 1, '主詞用動名詞 Waking。'),
('elementary', 'I would like ___ pizza slice.', '["A. other", "B. another", "C. others", "D. the other"]'::jsonb, 'B', 1, '再一片（不定數中再一個）用 another。'),
('elementary', 'Both answers ___ wrong. (choose the best option).', '["A. is", "B. are", "C. am", "D. was"]'::jsonb, 'B', 1, 'Both + 複數名詞用 are。'),
('elementary', 'Neither answer ___ correct. (choose the best option).', '["A. are", "B. is", "C. were", "D. be"]'::jsonb, 'B', 1, 'Neither + 單數名詞視為單數 is。'),
('elementary', 'Put your toys ___ the box. (choose the best option).', '["A. at", "B. on", "C. in", "D. to"]'::jsonb, 'C', 2, '放入盒子內部用 in。'),
('elementary', 'The poster is ___ the wall. (choose the best option).', '["A. in", "B. on", "C. at", "D. over"]'::jsonb, 'B', 1, '貼在牆面上用 on。'),
('elementary', 'We will meet ___ noon.', '["A. on", "B. in", "C. at", "D. by"]'::jsonb, 'C', 2, '時刻 at noon。'),
('elementary', '___ spring, flowers bloom. (choose the best option).', '["A. On", "B. At", "C. In", "D. By"]'::jsonb, 'C', 2, '季節用 in。'),
('elementary', 'We''re traveling ___ plane. (choose the best option).', '["A. by", "B. on", "C. with", "D. in"]'::jsonb, 'A', 0, '交通工具 by plane。'),
('elementary', 'I am afraid ___ spiders.', '["A. for", "B. of", "C. about", "D. with"]'::jsonb, 'B', 1, 'be afraid of。'),
('elementary', 'Could you please speak ___ slowly?', '["A. more", "B. many", "C. much", "D. most"]'::jsonb, 'A', 0, '請對方「再慢一點」用 more slowly。'),
('elementary', 'This puzzle is easy ___ me. (choose the best option).', '["A. for", "B. to", "C. with", "D. of"]'::jsonb, 'A', 0, '對某人而言簡單用 for。'),
('elementary', 'What is the opposite of ''cheap''?', '["A. small", "B. expensive", "C. short", "D. cold"]'::jsonb, 'B', 1, 'cheap 的反義常用 expensive。'),
('elementary', 'Which month comes ___ October (choose the best option)?', '["A. before", "B. after", "C. between", "D. during"]'::jsonb, 'B', 1, '十一月接在十月之後。'),
('elementary', 'A rectangle has ___ sides. (choose the best option).', '["A. three", "B. four", "C. five", "D. six"]'::jsonb, 'B', 1, '長方形四邊。'),
('elementary', 'Water freezes at ___ Celsius. (choose the best option).', '["A. 0", "B. 32", "C. 100", "D. 50"]'::jsonb, 'A', 0, '水的冰點攝氏 0 度。'),
('elementary', 'Which animal lives in water and jumps (choose the best option)?', '["A. lion", "B. frog", "C. cow", "D. eagle"]'::jsonb, 'B', 1, '青蛙典型在水邊／水中活動並跳躍。'),
('elementary', 'You cut vegetables with a ___. (choose the best option).', '["A. ball", "B. knife", "C. hat", "D. pillow"]'::jsonb, 'B', 1, '用刀切菜。'),
('elementary', 'We listen to music with our ___. (choose the best option).', '["A. eyes", "B. ears", "C. nose", "D. hands"]'::jsonb, 'B', 1, '耳朵聽音樂。'),
('elementary', 'What do you use to tell time (choose the best option)?', '["A. a map", "B. a clock", "C. a spoon", "D. a pillow"]'::jsonb, 'B', 1, '時鐘看時間。'),
('elementary', 'If you are hungry, you want ___. (choose the best option).', '["A. sleep", "B. food", "C. ice", "D. darkness"]'::jsonb, 'B', 1, '餓了想吃東西。'),
('elementary', 'This juice tastes ___. (choose the best option).', '["A. sweetly", "B. sweet", "C. sweetness", "D. sweeter"]'::jsonb, 'B', 1, '感官動詞 taste 後接形容詞 sweet。'),
('elementary', 'The baby seems ___. (choose the best option).', '["A. happily", "B. happy", "C. happiness", "D. more happy"]'::jsonb, 'B', 1, 'seem + 形容詞。'),
('elementary', '___ one is yours — the red or the blue (choose the best option)?', '["A. When", "B. Which", "C. What", "D. Who"]'::jsonb, 'B', 1, '在有限選擇中問哪一個用 Which。'),
('elementary', '___ father is a pilot (choose the best option)?', '["A. Who", "B. Whose", "C. Which", "D. What"]'::jsonb, 'B', 1, '問「誰的父親」用 Whose。'),
('elementary', 'Kindly ___ quiet in the hospital.', '["A. are", "B. be", "C. is", "D. being"]'::jsonb, 'B', 1, '祈使句用 Be quiet。'),
('elementary', 'Let us ___ the homework together.', '["A. do", "B. does", "C. doing", "D. did"]'::jsonb, 'A', 0, 'Let''s + 原形。'),
('elementary', 'Do not ___ your phone in class.', '["A. uses", "B. use", "C. using", "D. used"]'::jsonb, 'B', 1, 'Don''t + 原形。'),
('elementary', 'She forgot ___ her umbrella. (choose the best option).', '["A. bring", "B. to bring", "C. bringing", "D. brought"]'::jsonb, 'B', 1, 'forget to + 原形表忘了去做。'),
('elementary', 'Remember ___ the door. (choose the best option).', '["A. lock", "B. to lock", "C. locking", "D. locked"]'::jsonb, 'B', 1, 'remember to lock 記得要鎖。'),
('elementary', 'He wants ___ a pilot. (choose the best option).', '["A. be", "B. to be", "C. being", "D. been"]'::jsonb, 'B', 1, 'want to be。'),
('elementary', 'I am learning ___ swim.', '["A. for", "B. to", "C. how to", "D. how"]'::jsonb, 'C', 2, '學習如何游泳用 how to swim。'),
('elementary', 'It is important ___ sleep enough.', '["A. for", "B. to", "C. that", "D. of"]'::jsonb, 'B', 1, 'It''s important to + 原形。'),
('elementary', 'Could you please tell me the ___ ?', '["A. true", "B. truth", "C. truly", "D. truths"]'::jsonb, 'B', 1, 'tell the truth 說實話。'),
('elementary', 'There were ___ people at the park. (choose the best option).', '["A. much", "B. many", "C. a little", "D. little"]'::jsonb, 'B', 1, '可數 people 用 many。'),
('elementary', 'How ___ homework do you have (choose the best option)?', '["A. many", "B. much", "C. often", "D. long"]'::jsonb, 'B', 1, '不可數 homework 用 How much。'),
('elementary', 'Pick ___ apple from the basket. (choose the best option).', '["A. a", "B. an", "C. the", "D. no article"]'::jsonb, 'B', 1, 'apple 母音開頭用 an。'),
('junior', 'If it ___ tomorrow, we will cancel the trip. (choose the best option).', '["A. will rain", "B. rains", "C. rained", "D. rain"]'::jsonb, 'B', 1, '第一條件句 if + 現在，主句未來。'),
('junior', 'Unless you hurry, you ___ the train. (choose the best option).', '["A. catch", "B. will catch", "C. won''t catch", "D. caught"]'::jsonb, 'C', 2, 'Unless = if not，錯過車用未來否定。'),
('junior', 'By 2030, scientists believe many cars ___ electric. (choose the best option).', '["A. are", "B. were", "C. will be", "D. have been"]'::jsonb, 'C', 2, '未來時間用 will be。'),
('junior', 'She ___ since Monday. (choose the best option).', '["A. is sick", "B. has been sick", "C. was sick", "D. sicks"]'::jsonb, 'B', 1, 'since + 時間點用現在完成或完成進行；此處 has been sick。'),
('junior', 'I ___ my keys. Have you seen them (choose the best option)?', '["A. lost", "B. have lost", "C. had lost", "D. lose"]'::jsonb, 'B', 1, '剛剛丟了影響現在，現在完成。'),
('junior', 'This time yesterday I ___ on a bus. (choose the best option).', '["A. sit", "B. was sitting", "C. sat", "D. have sat"]'::jsonb, 'B', 1, '特定過去時刻進行用過去進行。'),
('junior', 'He suggested that she ___ early. (choose the best option).', '["A. leave", "B. leaves", "C. left", "D. leaving"]'::jsonb, 'A', 0, 'suggest that + 原形（英式）。'),
('junior', 'It is vital that everyone ___ quiet.', '["A. remain", "B. remains", "C. remained", "D. remaining"]'::jsonb, 'A', 0, 'vital that + (should) + 原形。'),
('junior', 'The roof ___ in last night''s storm. (choose the best option).', '["A. damages", "B. was damaged", "C. damaged", "D. has damaged"]'::jsonb, 'B', 1, '屋頂被損壞，過去被動。'),
('junior', 'The cake ___ by my sister. (choose the best option).', '["A. made", "B. was made", "C. makes", "D. making"]'::jsonb, 'B', 1, '蛋糕被製作，被動。'),
('junior', 'She admitted ___ the window. (choose the best option).', '["A. break", "B. breaking", "C. to break", "D. broke"]'::jsonb, 'B', 1, 'admit + 動名詞。'),
('junior', 'He avoided ___ her at the party. (choose the best option).', '["A. see", "B. seeing", "C. to see", "D. saw"]'::jsonb, 'B', 1, 'avoid + 動名詞。'),
('junior', 'I am planning ___ abroad next year.', '["A. study", "B. to study", "C. studying", "D. studied"]'::jsonb, 'B', 1, 'plan to + 原形。'),
('junior', 'She''s keen ___ learning Japanese. (choose the best option).', '["A. for", "B. on", "C. in", "D. at"]'::jsonb, 'B', 1, 'be keen on + 動名詞。'),
('junior', 'The movie was ___ boring that we left early. (choose the best option).', '["A. so", "B. such", "C. very", "D. too"]'::jsonb, 'A', 0, 'so...that 如此…以致。'),
('junior', 'It was ___ a boring movie that we left early. (choose the best option).', '["A. so", "B. such", "C. very", "D. much"]'::jsonb, 'B', 1, 'such + a + 形 + 名。'),
('junior', 'No sooner had we arrived ___ it started snowing. (choose the best option).', '["A. when", "B. than", "C. before", "D. until"]'::jsonb, 'B', 1, 'No sooner...than 固定。'),
('junior', 'Hardly had he spoken ___ someone interrupted. (choose the best option).', '["A. than", "B. when", "C. before", "D. after"]'::jsonb, 'B', 1, 'Hardly...when。'),
('junior', 'Were I you, I ___ accept the offer. (choose the best option).', '["A. will", "B. would", "C. can", "D. shall"]'::jsonb, 'B', 1, '虛擬與現在相反用 would。'),
('junior', 'I wish I ___ how to fix this. (choose the best option).', '["A. know", "B. knew", "C. have known", "D. knowing"]'::jsonb, 'B', 1, 'wish + 過去式表與現在願望相反。'),
('junior', 'I would rather you ___ here tonight.', '["A. stay", "B. stayed", "C. staying", "D. to stay"]'::jsonb, 'B', 1, 'would rather + 子句常用過去式表對他人期望。'),
('junior', 'The boy ___ wallet was lost cried. (choose the best option).', '["A. who", "B. whom", "C. whose", "D. which"]'::jsonb, 'C', 2, '所有格 whose wallet。'),
('junior', 'This is the factory ___ my uncle works. (choose the best option).', '["A. which", "B. where", "C. that", "D. what"]'::jsonb, 'B', 1, '地點先行詞 where。'),
('junior', 'She didn''t tell me ___ she was leaving. (choose the best option).', '["A. that", "B. if", "C. what", "D. which"]'::jsonb, 'B', 1, '是否離開用 if/whether。'),
('junior', '___ breaks the law must face consequences. (choose the best option).', '["A. Whoever", "B. Who", "C. Whomever", "D. Whatever"]'::jsonb, 'A', 0, '無論誰 whoever。'),
('junior', 'However hard he tried, he ___ pass. (choose the best option).', '["A. can''t", "B. couldn''t", "C. doesn''t", "D. won''t"]'::jsonb, 'B', 1, 'However hard，過去嘗試用 couldn''t。'),
('junior', 'The news ___ quite shocking. (choose the best option).', '["A. are", "B. were", "C. was", "D. be"]'::jsonb, 'C', 2, 'news 不可數單數。'),
('junior', 'Physics ___ my weakest subject. (choose the best option).', '["A. are", "B. were", "C. is", "D. be"]'::jsonb, 'C', 2, '學科 physics 單數。'),
('junior', 'Either Tom or his cousins ___ coming. (choose the best option).', '["A. is", "B. are", "C. was", "D. be"]'::jsonb, 'B', 1, 'either or 動詞與較近主詞一致。'),
('junior', 'Not only the coach but also the players ___ happy. (choose the best option).', '["A. was", "B. were", "C. is", "D. be"]'::jsonb, 'B', 1, 'but also 後 players 複數。'),
('junior', 'She speaks ___ she had rehearsed for hours. (choose the best option).', '["A. even if", "B. as if", "C. unless", "D. until"]'::jsonb, 'B', 1, '好像 as if。'),
('junior', 'The building ___ next year. (choose the best option).', '["A. completes", "B. will complete", "C. will be completed", "D. completed"]'::jsonb, 'C', 2, '明年被完工，未來被動。'),
('junior', 'I remember ___ the door before bed. (choose the best option).', '["A. lock", "B. to lock", "C. locking", "D. locked"]'::jsonb, 'C', 2, '記得做過 locking。'),
('junior', 'Kindly remember ___ the door before you leave.', '["A. lock", "B. to lock", "C. locking", "D. locked"]'::jsonb, 'B', 1, '記得要去做的尚未做，to lock。'),
('junior', 'He is used ___ early for his job. (choose the best option).', '["A. to get up", "B. to getting up", "C. get up", "D. getting up"]'::jsonb, 'B', 1, 'be used to + 動名詞表習慣。'),
('junior', 'He used ___ early before retirement. (choose the best option).', '["A. to get up", "B. to getting up", "C. get up", "D. getting up"]'::jsonb, 'A', 0, 'used to + 原形表過去習慣。'),
('junior', 'She got her brother ___ the heavy box. (choose the best option).', '["A. carry", "B. to carry", "C. carrying", "D. carried"]'::jsonb, 'B', 1, 'get + 人 + to + 原形。'),
('junior', 'We had the roof ___ after the storm. (choose the best option).', '["A. repair", "B. repaired", "C. repairing", "D. repairs"]'::jsonb, 'B', 1, 'have + 物 + 過去分詞。'),
('junior', 'The problem ___ at yesterday''s meeting. (choose the best option).', '["A. discusses", "B. was discussed", "C. discussed", "D. is discussing"]'::jsonb, 'B', 1, '問題被討論。'),
('junior', '___ careful when you cross the street. (choose the best option).', '["A. Be", "B. Being", "C. To be", "D. Been"]'::jsonb, 'A', 0, '祈使句 Be careful。'),
('junior', 'Reading: Tim forgot his keys and missed the bus. Why might Tim be late (choose the best option)?', '["A. He woke early", "B. He couldn''t enter his house fast", "C. He loves buses", "D. He ran fast"]'::jsonb, 'B', 1, '忘記鑰匙可能耽誤出門。'),
('junior', 'Reading: The café opens at 7 a.m. Does it open before 8 (choose the best option)?', '["A. No", "B. Yes", "C. Only on Sundays", "D. Unknown"]'::jsonb, 'B', 1, '七點開門，八點前已開。'),
('junior', 'Choose the closest meaning to ''generous''. (choose the best option).', '["A. greedy", "B. kind and giving", "C. shy", "D. strict"]'::jsonb, 'B', 1, 'generous 表示慷慨。'),
('junior', 'Choose the closest meaning to ''ancient''. (choose the best option).', '["A. modern", "B. very old", "C. tiny", "D. noisy"]'::jsonb, 'B', 1, 'ancient 古老。'),
('junior', 'She has ___ experience than I do. (choose the best option).', '["A. much", "B. more", "C. most", "D. many"]'::jsonb, 'B', 1, 'than 比較 more experience。'),
('junior', 'This is ___ difficult exam I''ve taken. (choose the best option).', '["A. more", "B. most", "C. the most", "D. much"]'::jsonb, 'C', 2, '最高級 the most difficult。'),
('junior', 'He speaks Spanish ___ than I do. (choose the best option).', '["A. fluent", "B. more fluently", "C. most fluent", "D. fluently"]'::jsonb, 'B', 1, '修飾動詞 speaks 用副詞比較。'),
('junior', 'I would ___ stay home than go out in this rain.', '["A. rather", "B. prefer", "C. better", "D. want"]'::jsonb, 'A', 0, 'would rather...than。'),
('junior', 'She''d prefer ___ alone tonight. (choose the best option).', '["A. be", "B. to be", "C. being", "D. been"]'::jsonb, 'B', 1, 'would prefer to be。'),
('junior', 'It is worth ___ the instructions twice.', '["A. read", "B. reading", "C. to read", "D. reads"]'::jsonb, 'B', 1, 'worth + 動名詞。'),
('junior', 'There''s no point in ___ over failed exams. (choose the best option).', '["A. worry", "B. worrying", "C. to worry", "D. worried"]'::jsonb, 'B', 1, 'no point in + 動名詞。'),
('junior', 'She prevented him ___ entering the room. (choose the best option).', '["A. from", "B. to", "C. for", "D. of"]'::jsonb, 'A', 0, 'prevent from + 動名詞。'),
('junior', 'The rain stopped them ___ playing tennis. (choose the best option).', '["A. from", "B. to", "C. of", "D. for"]'::jsonb, 'A', 0, 'stop from + 動名詞。'),
('junior', 'He congratulated me ___ winning. (choose the best option).', '["A. for", "B. on", "C. with", "D. about"]'::jsonb, 'B', 1, 'congratulate on + 動名詞。'),
('junior', 'She apologized ___ being rude. (choose the best option).', '["A. for", "B. to", "C. of", "D. about"]'::jsonb, 'A', 0, 'apologize for + 動名詞。'),
('junior', 'I am responsible ___ the schedule.', '["A. for", "B. of", "C. to", "D. with"]'::jsonb, 'A', 0, 'responsible for。'),
('junior', 'He''s addicted ___ online games. (choose the best option).', '["A. for", "B. to", "C. on", "D. with"]'::jsonb, 'B', 1, 'addicted to。'),
('junior', 'The teacher explained the rule ___ . (choose the best option).', '["A. clear", "B. clearly", "C. clearness", "D. clearer"]'::jsonb, 'B', 1, '修飾動詞 explained 用副詞。'),
('junior', 'She looked ___ when she heard the news. (choose the best option).', '["A. surprising", "B. surprised", "C. surprise", "D. surprisingly"]'::jsonb, 'B', 1, '形容人用 surprised。'),
('junior', 'The lecture was ___ tedious that several listeners left early. (choose the best option).', '["A. so", "B. such", "C. very", "D. too"]'::jsonb, 'A', 0, 'so...that 如此…以致；tedious 形前用 so。'),
('junior', 'Seldom ___ such a crowd here. (choose the best option).', '["A. we saw", "B. did we see", "C. we see", "D. have we seen"]'::jsonb, 'B', 1, 'Seldom 開頭倒裝。'),
('junior', 'Not until he apologized ___ she forgive him. (choose the best option).', '["A. she did", "B. did she", "C. she would", "D. would she"]'::jsonb, 'B', 1, 'Not until 子句後倒裝 did she。'),
('junior', 'Little ___ that he would become famous. (choose the best option).', '["A. he knows", "B. did he know", "C. he knew", "D. does he know"]'::jsonb, 'B', 1, 'Little 開頭倒裝。'),
('junior', 'So loudly ___ that everyone turned around. (choose the best option).', '["A. he spoke", "B. did he speak", "C. he speaks", "D. does he speak"]'::jsonb, 'B', 1, 'So loudly 前置倒裝。'),
('junior', 'If I ___ harder, I would pass right now.', '["A. study", "B. studied", "C. had studied", "D. have studied"]'::jsonb, 'B', 1, '與現在事實相反，過去式 studied。'),
('junior', 'If he ___ the map, he wouldn''t be lost. (choose the best option).', '["A. reads", "B. had read", "C. read", "D. has read"]'::jsonb, 'C', 2, '與過去事實相反用過去完成 had read。'),
('junior', 'The letter ___ personally by the CEO. (choose the best option).', '["A. writes", "B. was written", "C. wrote", "D. writing"]'::jsonb, 'B', 1, '信被撰寫／簽署語境用被動。'),
('junior', 'She ___ her ankle while jogging. (choose the best option).', '["A. breaks", "B. broke", "C. was breaking", "D. has broken"]'::jsonb, 'B', 1, '慢跑時扭傷，過去式 broke。'),
('junior', 'By next month, we ___ the project. (choose the best option).', '["A. finish", "B. will finish", "C. will have finished", "D. finished"]'::jsonb, 'C', 2, 'By + 未來完成。'),
('junior', 'He speaks English fluently; ___, he grew up abroad. (choose the best option).', '["A. because", "B. for example", "C. besides", "D. therefore"]'::jsonb, 'C', 2, '補充理由 besides／此外。'),
('junior', 'She failed the test; ___, she didn''t study. (choose the best option).', '["A. however", "B. therefore", "C. although", "D. unless"]'::jsonb, 'B', 1, '因果 therefore。'),
('junior', '___ the rain, the match continued. (choose the best option).', '["A. Because", "B. Despite", "C. Although", "D. Since"]'::jsonb, 'B', 1, '儘管下雨 despite + 名詞。'),
('junior', '___ it was raining, the match continued. (choose the best option).', '["A. Because", "B. Although", "C. Despite", "D. Unless"]'::jsonb, 'B', 1, '讓步 although + 子句。'),
('junior', 'You ___ touch the exhibits in the museum. (choose the best option).', '["A. should", "B. mustn''t", "C. might", "D. could"]'::jsonb, 'B', 1, '禁止觸摸 mustn''t。'),
('junior', 'Applicants ___ submit forms by Friday. (choose the best option).', '["A. can", "B. must", "C. might", "D. could"]'::jsonb, 'B', 1, '規定截止 must。'),
('college', 'The manuscript was ___ peer review last month. (choose the best option).', '["A. submit", "B. submitted", "C. submitting", "D. submits"]'::jsonb, 'B', 1, '過去被提交審查 submitted。'),
('college', 'The paper ___ several limitations. (choose the best option).', '["A. acknowledge", "B. acknowledges", "C. acknowledged", "D. acknowledging"]'::jsonb, 'C', 2, '過去式 acknowledged 限制。'),
('college', 'The authors ___ the funding agency. (choose the best option).', '["A. thank", "B. thanked", "C. thank to", "D. thanks"]'::jsonb, 'B', 1, '謝謝資助方 thanked。'),
('college', 'The experiment ___ ethical guidelines. (choose the best option).', '["A. follow", "B. followed", "C. was following", "D. follows"]'::jsonb, 'B', 1, '過去遵循 followed。'),
('college', 'Findings cannot be ___ without replication. (choose the best option).', '["A. generalize", "B. generalized", "C. generalizing", "D. generalizes"]'::jsonb, 'B', 1, '被概括 generalized。'),
('college', 'The hypothesis remains ___. (choose the best option).', '["A. test", "B. untested", "C. testing", "D. tests"]'::jsonb, 'B', 1, '形容詞未檢驗 untested。'),
('college', 'The correlation is statistically ___. (choose the best option).', '["A. significance", "B. significant", "C. significantly", "D. signify"]'::jsonb, 'B', 1, '形容詞補語 significant。'),
('college', 'The effect size was ___. (choose the best option).', '["A. substance", "B. substantial", "C. substantially", "D. substantiate"]'::jsonb, 'B', 1, '形容詞 substantial。'),
('college', 'The discussion ___ alternative explanations. (choose the best option).', '["A. address", "B. addresses", "C. addressed", "D. addressing"]'::jsonb, 'C', 2, '過去討論到 addressed。'),
('college', 'Future research should ___ these variables. (choose the best option).', '["A. examine", "B. examines", "C. examining", "D. examined"]'::jsonb, 'A', 0, '情態動詞後原形 examine。'),
('college', 'The variable was ___ controlled. (choose the best option).', '["A. careful", "B. carefully", "C. carefulness", "D. care"]'::jsonb, 'B', 1, '副詞修飾過去分詞。'),
('college', 'The outcome was ___ unexpected. (choose the best option).', '["A. somewhat", "B. somewhatly", "C. some", "D. somewhere"]'::jsonb, 'A', 0, '副詞 somewhat。'),
('college', 'The proposal was ___ rejected. (choose the best option).', '["A. unanimous", "B. unanimously", "C. unanimity", "D. unanimouslyness"]'::jsonb, 'B', 1, '副詞 unanimously。'),
('college', 'The framework is ___ applicable. (choose the best option).', '["A. broad", "B. broadly", "C. breadth", "D. broaden"]'::jsonb, 'B', 1, '修飾形容詞 broadly。'),
('college', 'The evidence ___ replication. (choose the best option).', '["A. warrant", "B. warrants", "C. warranted", "D. warranting"]'::jsonb, 'B', 1, '現在 warrants 值得。'),
('college', 'The sample was ___ drawn. (choose the best option).', '["A. random", "B. randomly", "C. randomness", "D. randomize"]'::jsonb, 'B', 1, '副詞 randomly。'),
('college', 'Participants gave ___ consent. (choose the best option).', '["A. inform", "B. informed", "C. informing", "D. informs"]'::jsonb, 'B', 1, '知情同意 informed consent。'),
('college', 'The interview data were ___ anonymized. (choose the best option).', '["A. full", "B. fully", "C. fulness", "D. fulfill"]'::jsonb, 'B', 1, '副詞 fully。'),
('college', 'The survey ___ response bias. (choose the best option).', '["A. may exhibit", "B. may exhibits", "C. might exhibited", "D. might exhibiting"]'::jsonb, 'A', 0, '可能呈現偏差 may exhibit。'),
('college', 'The article ___ prior work extensively. (choose the best option).', '["A. cite", "B. cites", "C. citing", "D. cited"]'::jsonb, 'D', 3, '過去引用 cited。'),
('college', 'The model ___ reality imperfectly. (choose the best option).', '["A. mirror", "B. mirrors", "C. mirrored", "D. mirroring"]'::jsonb, 'B', 1, '第三人稱 mirrors。'),
('college', 'The trend has ___ sharply. (choose the best option).', '["A. accelerate", "B. accelerated", "C. accelerating", "D. accelerates"]'::jsonb, 'B', 1, '現在完成 has accelerated。'),
('college', 'Inflation has ___ consumer spending recently. (choose the best option).', '["A. curb", "B. curbed", "C. curbing", "D. to curb"]'::jsonb, 'B', 1, '現在完成式 has + 過去分詞 curbed。'),
('college', 'Ethics approval ___ obtained before recruitment. (choose the best option).', '["A. was", "B. were", "C. is", "D. are"]'::jsonb, 'A', 0, '不可數／單數概念用 was obtained。'),
('college', 'Participants ___ debriefed after the study. (choose the best option).', '["A. was", "B. were", "C. is", "D. are"]'::jsonb, 'B', 1, '複數 participants 搭配 were。'),
('college', 'The findings ___ not generalizable beyond the sample. (choose the best option).', '["A. is", "B. are", "C. was", "D. be"]'::jsonb, 'B', 1, '複數 findings 用 are。'),
('college', 'The instrument demonstrates adequate ___. (choose the best option).', '["A. reliable", "B. reliability", "C. reliably", "D. relying"]'::jsonb, 'B', 1, '名詞 reliability 十足。'),
('college', 'Cronbach''s alpha reflects internal ___. (choose the best option).', '["A. consistent", "B. consistency", "C. consistently", "D. consistor"]'::jsonb, 'B', 1, '內部一致性 consistency。'),
('college', 'Multicollinearity can ___ coefficient estimates. (choose the best option).', '["A. bias", "B. distort", "C. distorts", "D. distorting"]'::jsonb, 'B', 1, '情態動詞後原形 distort。'),
('college', 'The regression assumes residuals are approximately ___. (choose the best option).', '["A. normal", "B. normally", "C. normality", "D. normalize"]'::jsonb, 'A', 0, '形容詞補語 normal。'),
('college', 'We conducted a pilot study ___ scale refinement. (choose the best option).', '["A. for", "B. to", "C. toward", "D. into"]'::jsonb, 'C', 2, '朝向／為了精煉 toward scale refinement。'),
('college', 'The literature review ___ gaps in prior studies. (choose the best option).', '["A. highlight", "B. highlights", "C. highlighted", "D. highlighting"]'::jsonb, 'C', 2, '過去式 highlighted。'),
('college', 'Item wording was revised ___ ambiguity. (choose the best option).', '["A. reduce", "B. to reduce", "C. reducing", "D. reduced"]'::jsonb, 'B', 1, '不定詞表目的 to reduce。'),
('college', 'Response categories were ___ labeled. (choose the best option).', '["A. clear", "B. clearly", "C. clearing", "D. clearness"]'::jsonb, 'B', 1, '副詞 clearly。'),
('college', 'Missing values were handled using listwise ___. (choose the best option).', '["A. delete", "B. deletion", "C. deleting", "D. deleted"]'::jsonb, 'B', 1, '名詞 deletion。'),
('college', 'The null hypothesis was ___ at α = .05. (choose the best option).', '["A. reject", "B. rejected", "C. rejecting", "D. rejects"]'::jsonb, 'B', 1, '被動 rejected。'),
('college', 'A Bonferroni correction ___ multiple comparisons. (choose the best option).', '["A. address", "B. addresses", "C. addressed", "D. addressing"]'::jsonb, 'B', 1, '第三人稱 addresses。'),
('college', 'Effect sizes are reported ___ p-values alone. (choose the best option).', '["A. beside", "B. alongside", "C. besides", "D. along"]'::jsonb, 'B', 1, 'alongside 與…並列。'),
('college', 'The abstract ___ the main outcomes. (choose the best option).', '["A. summarize", "B. summarizes", "C. summarized", "D. summarizing"]'::jsonb, 'C', 2, '過去式 summarized。'),
('college', 'Figures were produced using ___ software. (choose the best option).', '["A. statistical", "B. statistics", "C. statistically", "D. statistic"]'::jsonb, 'A', 0, '形容詞 statistical software。'),
('college', 'Limitations include ___ sampling bias. (choose the best option).', '["A. potential", "B. potentially", "C. potence", "D. potent"]'::jsonb, 'A', 0, '形容詞 potential。'),
('college', 'Future work might ___ longitudinal designs. (choose the best option).', '["A. employ", "B. employs", "C. employed", "D. employing"]'::jsonb, 'A', 0, '情態動詞後原形 employ。'),
('college', 'Confounding variables were ___ where possible. (choose the best option).', '["A. control", "B. controlled", "C. controlling", "D. controls"]'::jsonb, 'B', 1, '被動 controlled。'),
('college', 'The coding scheme achieved satisfactory ___. (choose the best option).', '["A. reliable", "B. reliability", "C. reliably", "D. rely"]'::jsonb, 'B', 1, '名詞 reliability。'),
('college', 'Inter-rater agreement was assessed using Cohen''s ___. (choose the best option).', '["A. kappa", "B. Kappa", "C. kappa coefficient", "D. kap"]'::jsonb, 'B', 1, '專有名詞 Kappa（選項一致即可）。'),
('college', 'The manuscript adheres to journal ___ guidelines. (choose the best option).', '["A. style", "B. styling", "C. stylish", "D. styles"]'::jsonb, 'A', 0, 'style guidelines 體例／格式指引。'),
('college', 'Prior informed consent was ___ in writing. (choose the best option).', '["A. obtain", "B. obtained", "C. obtaining", "D. obtains"]'::jsonb, 'B', 1, '被動 obtained。'),
('college', 'De-identified transcripts were stored ___. (choose the best option).', '["A. secure", "B. securely", "C. security", "D. secured"]'::jsonb, 'B', 1, '副詞 securely。'),
('college', 'Qualitative themes emerged through ___. (choose the best option).', '["A. thematic", "B. thematic analysis", "C. themes", "D. theming"]'::jsonb, 'B', 1, '慣用 thematic analysis。'),
('college', 'Member checking ___ interpretive validity. (choose the best option).', '["A. enhance", "B. enhances", "C. enhanced", "D. enhancing"]'::jsonb, 'B', 1, '第三人稱 enhances。'),
('college', 'Saturation was reached when no new ___ appeared. (choose the best option).', '["A. theme", "B. themes", "C. thematic", "D. theming"]'::jsonb, 'B', 1, '複數 themes。'),
('college', 'NVivo was used to facilitate ___. (choose the best option).', '["A. code", "B. coding", "C. coded", "D. codify"]'::jsonb, 'B', 1, '動名詞 coding。'),
('college', 'The audit trail documents analytic ___. (choose the best option).', '["A. decide", "B. decisions", "C. deciding", "D. decided"]'::jsonb, 'B', 1, 'decisions。'),
('college', 'Reflexivity statements acknowledge researcher ___. (choose the best option).', '["A. bias", "B. biases", "C. biased", "D. biasing"]'::jsonb, 'A', 0, '不可數 bias。'),
('college', 'Positionality may ___ how findings are framed. (choose the best option).', '["A. shape", "B. shapes", "C. shaped", "D. shaping"]'::jsonb, 'B', 1, 'may + 原形 shape。'),
('college', 'Triangulation combined interviews with ___. (choose the best option).', '["A. observe", "B. observations", "C. observed", "D. observing"]'::jsonb, 'B', 1, '名詞 observations。'),
('college', 'Transferability depends on thick ___. (choose the best option).', '["A. describe", "B. description", "C. describing", "D. described"]'::jsonb, 'B', 1, 'thick description。'),
('college', 'Quantitative results were triangulated ___ survey comments. (choose the best option).', '["A. for", "B. with", "C. to", "D. by"]'::jsonb, 'B', 1, 'triangulated with。'),
('college', 'The discussion synthesizes results ___ prior theory. (choose the best option).', '["A. against", "B. with", "C. for", "D. under"]'::jsonb, 'B', 1, 'synthesize with theory。'),
('college', 'Preregistration ___ hypothesis specification. (choose the best option).', '["A. aid", "B. aids", "C. aided", "D. aiding"]'::jsonb, 'B', 1, '第三人稱 aids。'),
('college', 'An open science repository hosts the ___. (choose the best option).', '["A. datum", "B. data", "C. datas", "D. database"]'::jsonb, 'B', 1, '複數 data。'),
('college', 'Replication materials are available ___ request. (choose the best option).', '["A. in", "B. on", "C. upon", "D. for"]'::jsonb, 'C', 2, 'upon request 固定用法。'),
('college', 'Conflict-of-interest disclosures were ___. (choose the best option).', '["A. provide", "B. provided", "C. providing", "D. provides"]'::jsonb, 'B', 1, '被動 provided。'),
('college', 'Funding sources did not ___ study design. (choose the best option).', '["A. influence", "B. influences", "C. influenced", "D. influencing"]'::jsonb, 'A', 0, 'did not + 原形 influence。'),
('college', 'Author contributions follow CRediT ___. (choose the best option).', '["A. taxonomy", "B. taxonomies", "C. taxonomic", "D. taxon"]'::jsonb, 'A', 0, 'CRediT taxonomy。'),
('college', 'ORCID iDs ___ verified where available. (choose the best option).', '["A. is", "B. are", "C. was", "D. were"]'::jsonb, 'B', 1, '複數 ORCID iDs 用 were。'),
('college', 'Preprints were posted ___ peer review. (choose the best option).', '["A. before", "B. after", "C. during", "D. since"]'::jsonb, 'A', 0, '審查前 before peer review。'),
('college', 'The dataset ___ released under CC-BY. (choose the best option).', '["A. is", "B. are", "C. was", "D. were"]'::jsonb, 'C', 2, '過去釋出 was released。'),
('college', 'Sensitive variables were ___ to protect privacy. (choose the best option).', '["A. suppress", "B. suppressed", "C. suppressing", "D. suppresses"]'::jsonb, 'B', 1, '被動 suppressed。'),
('college', 'Statistical code was written ___ R. (choose the best option).', '["A. on", "B. at", "C. in", "D. by"]'::jsonb, 'C', 2, '用某語言 in R。'),
('college', 'Robustness checks ___ alternative specifications. (choose the best option).', '["A. use", "B. uses", "C. used", "D. using"]'::jsonb, 'C', 2, '過去式 used。'),
('college', 'Standard errors were clustered at the ___ level. (choose the best option).', '["A. firm", "B. firm-year", "C. firm level", "D. firmly"]'::jsonb, 'A', 0, '公司層級 firm level。'),
('college', 'An instrumental variable addresses ___. (choose the best option).', '["A. omit variable bias", "B. endogeneity", "C. randomness", "D. multicollinearity"]'::jsonb, 'B', 1, '工具變數處理內生性 endogeneity。'),
('college', 'The placebo test yields ___ results. (choose the best option).', '["A. null", "B. nullifying", "C. nullified", "D. nullity"]'::jsonb, 'A', 0, 'null results 無效應結果。'),
('college', 'Sensitivity analyses ___ the baseline estimates. (choose the best option).', '["A. confirm", "B. confirms", "C. confirmed", "D. confirming"]'::jsonb, 'C', 2, '過去式 confirmed。'),
('professor', 'Grice''s maxim of relation counsels speakers to be ___. (choose the best option).', '["A. verbose", "B. relevant", "C. polite only", "D. ambiguous"]'::jsonb, 'B', 1, '關聯準則要求相關 relevant。'),
('professor', 'In pragmatics, an implicature is often ___. (choose the best option).', '["A. entailed", "B. cancelable", "C. always explicit", "D. unrelated"]'::jsonb, 'B', 1, '含意通常可撤銷 cancelable。'),
('professor', 'A performative utterance ___. (choose the best option).', '["A. cannot be spoken", "B. can accomplish an act by being spoken", "C. must be false", "D. is always indirect"]'::jsonb, 'B', 1, '言語行為以說出即完成。'),
('professor', 'Relevance theory treats ostensive communication as ___. (choose the best option).', '["A. purely syntactic", "B. minimizing processing effort as assumed intended", "C. avoiding inference", "D. only literal"]'::jsonb, 'B', 1, '具展示性溝通涉及最佳相關與處理成本。'),
('professor', 'In phonology, complementary distribution suggests ___. (choose the best option).', '["A. free variation", "B. allophones of one phoneme", "C. minimal pairs", "D. tone sandhi always"]'::jsonb, 'B', 1, '互補分布常為同一音位之異音。'),
('professor', 'Metrical stress in English is typically ___. (choose the best option).', '["A. fixed on the first syllable always", "B. assigned within words according to lexical rules", "C. random", "D. suffix-driven only"]'::jsonb, 'B', 1, '英語重音受詞彙規則約束。'),
('professor', 'Binding theory primarily regulates ___. (choose the best option).', '["A. word order", "B. anaphor-pronoun dependencies", "C. question formation", "D. spell-out"]'::jsonb, 'B', 1, '管Binding／照應與代名詞依賴。'),
('professor', 'The EPP (Extended Projection Principle) concerns ___. (choose the best option).', '["A. theta roles only", "B. subjects at Spec-TP", "C. phonetic transcription", "D. discourse particles"]'::jsonb, 'B', 1, 'EPP 與主語／Spec-TP 相關。'),
('professor', 'In OT syntax, higher-ranked constraints ___. (choose the best option).', '["A. can be freely violated", "B. dominate lower-ranked ones", "C. are never evaluated", "D. apply only to morphology"]'::jsonb, 'B', 1, '優排序語法：高階限制優先。'),
('professor', 'VP ellipsis identity typically requires ___. (choose the best option).', '["A. verbatim repetition only", "B. parallelism at the relevant structural level", "C. no licensing", "D. modal verbs"]'::jsonb, 'B', 1, 'VP 省略需結構平行。'),
('professor', 'Parasitic gaps are licensed only when ___. (choose the best option).', '["A. no wh-movement occurs", "B. a true gap licenses wh-dependencies", "C. subjects are null", "D. infinitives are banned"]'::jsonb, 'B', 1, '寄生空缺依賴真正空缺／移位結構。'),
('professor', 'The cartographic approach maps functional heads onto ___. (choose the best option).', '["A. single phrase", "B. fine-grained hierarchies", "C. phonetic grids", "D. random trees"]'::jsonb, 'B', 1, '製圖式句法：細緻功能層級。'),
('professor', 'In Distributed Morphology, vocabulary insertion occurs ___. (choose the best option).', '["A. before syntax", "B. after syntax", "C. only in phonetics", "D. never"]'::jsonb, 'B', 1, '詞彙插入於句法之後。'),
('professor', 'Root suppletion mainly affects ___. (choose the best option).', '["A. determiners", "B. exponents realizing irregular stems", "C. intonation", "D. prosodic boundaries"]'::jsonb, 'B', 1, '詞根異干替換多見於不規則詞形。'),
('professor', 'In cognitive semantics, conceptual metaphor maps ___. (choose the best option).', '["A. sound to color only", "B. domains onto domains", "C. syntax to morphology", "D. alphabet to phonetics"]'::jsonb, 'B', 1, '概念隱喻跨域映射。'),
('professor', 'Frame semantics emphasizes ___. (choose the best option).', '["A. rhyme", "B. knowledge structures activated by words", "C. IPA charts", "D. stress grids"]'::jsonb, 'B', 1, '框架語義：詞所喚起知識結構。'),
('professor', 'Prototype theory predicts ___. (choose the best option).', '["A. crisp boundaries always", "B. graded category membership", "C. no polysemy", "D. uniform definitions"]'::jsonb, 'B', 1, '原型範疇具程度性。'),
('professor', 'Relevance in translation studies may prioritize ___. (choose the best option).', '["A. word-for-word gloss only", "B. functional equivalence in context", "C. ignoring register", "D. literal cognates"]'::jsonb, 'B', 1, '功能對等／語境等效。'),
('professor', 'Skopos theory foregrounds ___. (choose the best option).', '["A. author biography only", "B. the purpose of the translation task", "C. avoiding footnotes", "D. orthographic unity"]'::jsonb, 'B', 1, '目的論強調翻譯目的。'),
('professor', 'Corpus stylistics often relies on ___. (choose the best option).', '["A. intuition only", "B. frequency and collocational patterns", "C. rhyme schemes alone", "D. handwritten drafts"]'::jsonb, 'B', 1, '語料庫頻率與搭配。'),
('professor', 'In narratology, focalization concerns ___. (choose the best option).', '["A. camera lenses", "B. who perceives in the narrative", "C. chapter length", "D. typesetting"]'::jsonb, 'B', 1, '聚焦：誰在感知。'),
('professor', 'Free indirect discourse blends ___. (choose the best option).', '["A. only dialogue tags", "B. third-person narration with character-limited perspective", "C. stage directions", "D. footnotes"]'::jsonb, 'B', 1, '自由間接引語融合敘述與角色視角。'),
('professor', 'In rhetoric, aposiopesis stops mid-utterance to imply ___. (choose the best option).', '["A. strong emotion or discretion", "B. perfect grammar", "C. rhyme scheme", "D. IPA transcription"]'::jsonb, 'A', 0, '頓挫省略暗示強烈情感或保留。'),
('professor', 'An epic simile is characteristically ___. (choose the best option).', '["A. one line long", "B. extended and elaborate", "C. always humorous", "D. non-metaphorical"]'::jsonb, 'B', 1, '史詩明喻冗長細緻。'),
('professor', 'Horatian satire tends to be ___. (choose the best option).', '["A. bitter and violent", "B. urbane and tolerant", "C. purely tragic", "D. non-political always"]'::jsonb, 'B', 1, '賀拉斯式較溫和城市化。'),
('professor', 'Juvenalian satire tends toward ___. (choose the best option).', '["A. gentle mockery only", "B. indignation and harsh attack", "C. pastoral calm", "D. pure description"]'::jsonb, 'B', 1, '朱維納爾式較激烈譴責。'),
('professor', 'Metonymy substitutes ___. (choose the best option).', '["A. opposites", "B. a contiguous associated entity for another", "C. foreign words", "D. rhymes"]'::jsonb, 'B', 1, '借代：鄰近相關。'),
('professor', 'Synecdoche often substitutes ___. (choose the best option).', '["A. unrelated words", "B. part for whole or vice versa", "C. synonyms only", "D. verbs for nouns"]'::jsonb, 'B', 1, '提喻：部分代整體等。'),
('professor', 'Zeugma yokes ___. (choose the best option).', '["A. random clauses", "B. one word to two incongruous meanings", "C. only parallel nouns", "D. identical sounds"]'::jsonb, 'B', 1, '共軛／軛式搭配雙義。'),
('professor', 'Chiasmus depends on ___. (choose the best option).', '["A. rhyme only", "B. reversed parallel structure", "C. alliteration only", "D. homophones"]'::jsonb, 'B', 1, '交錯配對 reversed parallelism。'),
('professor', 'Aporia in rhetoric signals ___. (choose the best option).', '["A. certainty", "B. a feigned or genuine difficulty", "C. a bibliography", "D. meter"]'::jsonb, 'B', 1, '疑惑／難題 aporia。'),
('professor', 'An epistemic modal scopes over ___. (choose the best option).', '["A. only tense", "B. the speaker''s degree of commitment", "C. only aspect", "D. only objects"]'::jsonb, 'B', 1, '認識情態：說話者確信度。'),
('professor', 'Root modals often concern ___. (choose the best option).', '["A. pure tense", "B. permission, ability, or obligation", "C. only articles", "D. only word stress"]'::jsonb, 'B', 1, '根情態：許可能力義務等。'),
('professor', 'Scalar implicature arises from ___. (choose the best option).', '["A. spelling rules", "B. Gricean reasoning about stronger alternatives on a scale", "C. only idioms", "D. only phonology"]'::jsonb, 'B', 1, '量級含意源於較強選項。'),
('professor', 'In acquisition research, ''more + adjective'' often evidences ___. (choose the best option).', '["A. fossilization only", "B. movement toward comparative marking", "C. telegraphic omission only", "D. final devoicing"]'::jsonb, 'B', 1, 'more + 形 表比較結構習得。'),
('professor', 'The subset principle proposes learners prefer ___. (choose the best option).', '["A. the largest grammar", "B. the smallest grammar consistent with input", "C. random rules", "D. borrowings"]'::jsonb, 'B', 1, '子集原則偏好較小文法。'),
('professor', 'Positive evidence typically refers to ___. (choose the best option).', '["A. explicit correction only", "B. attested utterances learners encounter", "C. phonetic charts", "D. dictionary definitions only"]'::jsonb, 'B', 1, '正面證據：可及語料。'),
('professor', 'Negative evidence includes ___. (choose the best option).', '["A. only praise", "B. feedback marking ungrammaticality", "C. random noise", "D. translation only"]'::jsonb, 'B', 1, '負面證據：標示不合語法。'),
('professor', 'Poverty of the stimulus arguments target ___. (choose the best option).', '["A. behaviorist imitation only", "B. whether input suffices for acquisition as modeled", "C. only orthography", "D. only bilingual lexicons"]'::jsonb, 'B', 1, '刺激貧乏論證：輸入是否足夠。'),
('professor', 'Mirror neurons are debated regarding ___. (choose the best option).', '["A. spelling", "B. action understanding and simulation", "C. IPA transcription", "D. tone sandhi"]'::jsonb, 'B', 1, '鏡像神經元與動作理解。'),
('professor', 'In ERP studies, N400 amplitude often indexes ___. (choose the best option).', '["A. motor planning", "B. semantic expectancy violation", "C. pure motor reflex", "D. eye color"]'::jsonb, 'B', 1, 'N400 與語義期待違反。'),
('professor', 'LAN components are linked with ___. (choose the best option).', '["A. only happiness", "B. syntactic morphosyntactic anomalies", "C. only musical pitch", "D. only color naming"]'::jsonb, 'B', 1, '左前負波與句法異常。'),
('professor', 'P600 is commonly associated with ___. (choose the best option).', '["A. only breathing rate", "B. syntactic reanalysis or repair", "C. only olfaction", "D. only rhythm"]'::jsonb, 'B', 1, 'P600 與句法重分析。'),
('professor', 'In sociolinguistics, overt prestige aligns with ___. (choose the best option).', '["A. covert norms only", "B. institutionally endorsed norms", "C. only children''s speech", "D. only slang"]'::jsonb, 'B', 1, '外顯聲望：制度化規範。'),
('professor', 'Covert prestige may valorize ___. (choose the best option).', '["A. only formal registers", "B. local vernacular norms", "C. only spelling", "D. only loanwords"]'::jsonb, 'B', 1, '隱性聲望：在地規範。'),
('professor', 'Acts of identity theory stresses ___. (choose the best option).', '["A. random drift", "B. speakers using language to construct selves", "C. only phonetics", "D. only etymology"]'::jsonb, 'B', 1, '語言作為身分建構。'),
('professor', 'The observer''s paradox complicates ___. (choose the best option).', '["A. typing speed", "B. collecting natural speech while being observed", "C. only reading tests", "D. only word lists"]'::jsonb, 'B', 1, '觀察者悖論影響語料自然度。'),
('professor', 'Labovian style-shifting shows ___. (choose the best option).', '["A. no variation", "B. attention paid to speech affects formality", "C. only borrowing", "D. only syntax"]'::jsonb, 'B', 1, '注意力影響語體轉換。'),
('professor', 'Semantic narrowing historically often yields ___. (choose the best option).', '["A. broader meaning always", "B. more specific meanings from broader ones", "C. only synonyms", "D. only homophones"]'::jsonb, 'B', 1, '語義窄化。'),
('professor', 'Semantic widening can produce ___. (choose the best option).', '["A. only technical jargon", "B. broader senses from narrower ones", "C. only spelling changes", "D. only stress shifts"]'::jsonb, 'B', 1, '語義擴寬。'),
('professor', 'Pejoration describes ___. (choose the best option).', '["A. neutralization only", "B. meaning becoming more negative", "C. only vowel shifts", "D. only stress movement"]'::jsonb, 'B', 1, '貶義化。'),
('professor', 'Amelioration describes ___. (choose the best option).', '["A. meaning becoming more positive", "B. semantic bleaching only", "C. only metaphor death", "D. only accent loss"]'::jsonb, 'A', 0, '褒義化（意義變更正面）。'),
('professor', 'Deixis anchors meaning to ___. (choose the best option).', '["A. only dictionaries", "B. utterance context like time, place, speaker", "C. only phonemes", "D. only syllables"]'::jsonb, 'B', 1, '指示語境座標。'),
('professor', 'Analyticity in philosophy of language often pairs with ___. (choose the best option).', '["A. thick ethical concepts only", "B. truth by virtue of meaning", "C. only empirical measurement", "D. only proper names"]'::jsonb, 'B', 1, '分析性：依意義為真。'),
('professor', 'Rigid designation (Kripke) targets ___. (choose the best option).', '["A. all predicates", "B. referential stability across worlds for proper names", "C. only adjectives", "D. only tense"]'::jsonb, 'B', 1, '專名剛性指稱。'),
('professor', 'Two-dimensional semantics distinguishes ___. (choose the best option).', '["A. only tense and aspect", "B. epistemic vs metaphysical intensions", "C. only orthography", "D. only syllable weight"]'::jsonb, 'B', 1, '二維語義：認識／形上內涵。'),
('professor', 'Dynamic semantics models meaning as ___. (choose the best option).', '["A. static sets only", "B. context change potentials", "C. only phonetic strings", "D. only etymology trees"]'::jsonb, 'B', 1, '動態語義：脈絡更新潛能。'),
('professor', 'Montague grammar aims to ___. (choose the best option).', '["A. avoid logic", "B. compose sentence meanings via systematic rules", "C. replace phonetics", "D. ban quantifiers"]'::jsonb, 'B', 1, '蒙塔古語法：系統組合意義。'),
('professor', 'Generalized quantifiers treat noun phrases as ___. (choose the best option).', '["A. only predicates", "B. relations between sets", "C. only pronouns", "D. only determiners as heads"]'::jsonb, 'B', 1, '廣義量化詞：集合關係。'),
('professor', 'Presupposition projection investigates ___. (choose the best option).', '["A. only spelling", "B. how complex sentences inherit presuppositions", "C. only intonation", "D. only rhyme"]'::jsonb, 'B', 1, '預設投射。'),
('professor', 'Donkey anaphora challenges ___. (choose the best option).', '["A. only spelling rules", "B. simple treatments of indefinites and pronouns", "C. only tense", "D. only proper nouns"]'::jsonb, 'B', 1, '驢子句照應難題。'),
('professor', 'Dynamic predicate logic can represent ___. (choose the best option).', '["A. only idioms", "B. anaphora via discourse referents", "C. only IPA", "D. only stress"]'::jsonb, 'B', 1, '動態邏輯表照應。'),
('professor', 'Situation semantics replaces possible worlds with ___. (choose the best option).', '["A. only dictionaries", "B. situations as partial information states", "C. only syllables", "D. only rhyme schemes"]'::jsonb, 'B', 1, '情境語義：局部資訊情境。'),
('professor', 'Truthmaker semantics ties truth to ___. (choose the best option).', '["A. only syntax trees", "B. what makes sentences true", "C. only phonetics", "D. only etymology"]'::jsonb, 'B', 1, '使真者語義。'),
('professor', 'Supervaluationism handles vagueness by ___. (choose the best option).', '["A. banning logic", "B. quantifying over admissible sharpenings", "C. only dictionaries", "D. only homophones"]'::jsonb, 'B', 1, '超評估值：可容許細化。'),
('professor', 'Type-logical approaches link syntax and semantics via ___. (choose the best option).', '["A. random mapping", "B. curry-howard style proofs", "C. only stress", "D. only orthography"]'::jsonb, 'B', 1, '類型邏輯／句法語義介面。'),
('professor', 'Proof-theoretic semantics privileges ___. (choose the best option).', '["A. only dictionaries", "B. inferential rules over truth conditions alone", "C. only orthography", "D. only IPA"]'::jsonb, 'B', 1, '證明論語義：推導規則。'),
('professor', 'Lexical semantics decomposition debates whether features are ___. (choose the best option).', '["A. always universal across languages", "B. language-particular or universal", "C. only phonetic", "D. only orthographic"]'::jsonb, 'B', 1, '詞彙分解：特徵是否普世。'),
('professor', 'Polysemy networks are often modeled as ___. (choose the best option).', '["A. isolated lists", "B. radial categories with motivated extensions", "C. only rhyme pairs", "D. only homonyms"]'::jsonb, 'B', 1, '多義網路：放射狀範疇。'),
('professor', 'Construction grammar treats ___ as basic. (choose the best option).', '["A. only morphemes", "B. form-meaning pairings at multiple sizes", "C. only syllables", "D. only phonemes"]'::jsonb, 'B', 1, '構式語法：多層級形義配對。'),
('professor', 'Grammaticalization typically involves ___. (choose the best option).', '["A. only borrowing", "B. semantic bleaching and category shifts", "C. only stress movement", "D. only spelling reform"]'::jsonb, 'B', 1, '語法化：語義淡化與範疇轉移。'),
('professor', 'Grammaticalization clines suggest change is ___. (choose the best option).', '["A. instantaneous always", "B. gradient rather than strictly abrupt", "C. only phonetic", "D. only lexical"]'::jsonb, 'B', 1, '斜坡／漸變。'),
('professor', 'Areal diffusion explains ___. (choose the best option).', '["A. only genetic relationships", "B. similarities via contact between languages", "C. only universal grammar", "D. only orthography"]'::jsonb, 'B', 1, '區域擴散：接觸相似。'),
('professor', 'Substrate influence often surfaces in ___. (choose the best option).', '["A. only genetic trees", "B. lexicon and phonology of a dominant language", "C. only tense", "D. only spelling"]'::jsonb, 'B', 1, '底層語影響。'),
('professor', 'Diachronic reconstruction uses ___. (choose the best option).', '["A. only modern dictionaries", "B. the comparative method among cognates", "C. only rhyme", "D. only stress"]'::jsonb, 'B', 1, '歷史比較法。');
