INSERT INTO questions (difficulty, question_text, options, correct_answer_old, correct_index, explanation) VALUES
('elementary', 'I ___ a student.', '["A. am", "B. is", "C. are", "D. be"]'::jsonb, 'A', 0, '主詞 I 搭配 be 動詞 am。'),
('elementary', 'She ___ my sister.', '["A. am", "B. is", "C. are", "D. be"]'::jsonb, 'B', 1, '第三人稱單數 she 用 is。'),
('elementary', 'They ___ playing soccer.', '["A. is", "B. am", "C. are", "D. be"]'::jsonb, 'C', 2, '複數主詞 they 用 are。'),
('elementary', 'What ___ your name?', '["A. are", "B. is", "C. am", "D. be"]'::jsonb, 'B', 1, '單數主詞 your name 視為單一概念，用 is。'),
('elementary', 'There ___ five apples.', '["A. is", "B. are", "C. am", "D. be"]'::jsonb, 'B', 1, '後接複數名詞用 there are。'),
('elementary', 'He ___ not like coffee.', '["A. do", "B. does", "C. is", "D. are"]'::jsonb, 'B', 1, '第三人稱否定喜好用 does not。'),
('elementary', '___ you like tea?', '["A. Do", "B. Does", "C. Is", "D. Are"]'::jsonb, 'A', 0, 'you 搭配助動詞 Do 構成疑問。'),
('elementary', 'I have ___ umbrella.', '["A. a", "B. an", "C. the", "D. no article"]'::jsonb, 'B', 1, 'umbrella 母音開頭，冠詞用 an。'),
('elementary', 'This is ___ book.', '["A. a", "B. an", "C. the", "D. no article"]'::jsonb, 'A', 0, 'book 子音開頭，不定冠詞用 a。'),
('elementary', 'Those ___ my shoes.', '["A. is", "B. are", "C. am", "D. be"]'::jsonb, 'B', 1, 'those 為複數指示代名詞，動詞用 are。'),
('elementary', 'She ___ to school every day.', '["A. go", "B. goes", "C. going", "D. went"]'::jsonb, 'B', 1, '每天習慣用現在簡單式，she 加 -es。'),
('elementary', 'We ___ English on Mondays.', '["A. study", "B. studies", "C. studying", "D. studied"]'::jsonb, 'A', 0, 'We 為複數主詞，動詞用原形 study。'),
('elementary', 'It ___ raining now.', '["A. is", "B. are", "C. am", "D. be"]'::jsonb, 'A', 0, '現在進行式：It is + V-ing。'),
('elementary', 'Can you ___ me?', '["A. help", "B. helps", "C. helping", "D. helped"]'::jsonb, 'A', 0, '情態動詞 can 後接動詞原形。'),
('elementary', 'I ___ breakfast at 7 a.m.', '["A. eat", "B. eats", "C. eating", "D. ate"]'::jsonb, 'A', 0, 'I 第一人稱，現在簡單式用 eat。'),
('elementary', 'He ___ his homework yesterday.', '["A. do", "B. does", "C. did", "D. doing"]'::jsonb, 'C', 2, 'yesterday 表過去，助動詞用 did（此處選項為過去式動詞 did 表「做」—若題幹為 finish 類會不同；此題選 did 表完成過去動作）。'),
('elementary', 'They ___ TV last night.', '["A. watch", "B. watches", "C. watching", "D. watched"]'::jsonb, 'D', 3, 'last night 過去時間，動詞用過去式 watched。'),
('elementary', '___ is your birthday?', '["A. When", "B. Where", "C. Who", "D. How"]'::jsonb, 'A', 0, '詢問日期用 When。'),
('elementary', '___ bag is this?', '["A. Who", "B. Whose", "C. Which", "D. What"]'::jsonb, 'B', 1, '詢問物品所屬用 Whose。'),
('elementary', 'I am ___ years old.', '["A. seven", "B. seventh", "C. sevens", "D. sevenths"]'::jsonb, 'A', 0, '年齡用基數詞 seven。'),
('elementary', 'The cat is ___ the table.', '["A. in", "B. on", "C. at", "D. of"]'::jsonb, 'B', 1, '在桌面上用介系詞 on。'),
('elementary', 'The keys are ___ my pocket.', '["A. on", "B. in", "C. at", "D. by"]'::jsonb, 'B', 1, '在口袋內部用 in。'),
('elementary', 'She goes to school ___ bus.', '["A. by", "B. on", "C. in", "D. with"]'::jsonb, 'A', 0, '交通工具用 by bus。'),
('elementary', '___! You won the game.', '["A. Congratulations", "B. Sorry", "C. Excuse me", "D. Goodbye"]'::jsonb, 'A', 0, '祝賀對方獲勝用 Congratulations。'),
('elementary', 'It''s cold. Please ___ the window.', '["A. open", "B. opens", "C. opening", "D. opened"]'::jsonb, 'A', 0, '祈使句請求，動詞用原形 open。'),
('elementary', 'Don''t ___ in the library.', '["A. talk", "B. talks", "C. talking", "D. talked"]'::jsonb, 'A', 0, '否定祈使 Don''t 後接動詞原形。'),
('elementary', 'How ___ apples do you want?', '["A. much", "B. many", "C. old", "D. long"]'::jsonb, 'B', 1, '可數名詞數量用 How many。'),
('elementary', 'How ___ water do you need?', '["A. many", "B. much", "C. often", "D. far"]'::jsonb, 'B', 1, '不可數名詞用量用 How much。'),
('elementary', 'I have ___ brother and two sisters.', '["A. one", "B. an", "C. much", "D. any"]'::jsonb, 'A', 0, '一位哥哥／弟弟用 one 或 a；選項 one 正確。'),
('elementary', 'This pencil is ___.', '["A. you", "B. your", "C. yours", "D. you''re"]'::jsonb, 'C', 2, '名詞後表示「你的（東西）」用名詞性物主代名詞 yours。'),
('elementary', '___ pen is on the floor?', '["A. Who", "B. Whose", "C. Where", "D. When"]'::jsonb, 'B', 1, '問「誰的筆」用 Whose。'),
('elementary', 'We should ___ our teeth before bed.', '["A. brush", "B. brushes", "C. brushing", "D. brushed"]'::jsonb, 'A', 0, '情態動詞 should 後接原形 brush。'),
('elementary', 'It''s 10 p.m. Let''s ___ to bed.', '["A. go", "B. goes", "C. going", "D. went"]'::jsonb, 'A', 0, 'Let''s 後接動詞原形 go。'),
('elementary', 'The sun ___ in the east.', '["A. rise", "B. rises", "C. rising", "D. rose"]'::jsonb, 'B', 1, '自然現象習慣用現在式，the sun 為單數用 rises。'),
('elementary', 'Birds can ___.', '["A. fly", "B. flies", "C. flying", "D. flew"]'::jsonb, 'A', 0, '情態動詞 can 後接原形 fly。'),
('elementary', 'I want ___ apple juice.', '["A. a", "B. an", "C. some", "D. any"]'::jsonb, 'C', 2, '不可數的果汁表示「一些」用 some（肯定句）。'),
('elementary', 'There isn''t ___ milk in the fridge.', '["A. some", "B. any", "C. many", "D. a"]'::jsonb, 'B', 1, '否定句中「任何」用 any。'),
('elementary', 'My father ___ tall.', '["A. am", "B. is", "C. are", "D. be"]'::jsonb, 'B', 1, 'My father 第三人稱單數用 is。'),
('elementary', 'These ___ not my books.', '["A. is", "B. are", "C. am", "D. be"]'::jsonb, 'B', 1, 'these 複數用 are。'),
('elementary', '___ you OK?', '["A. Is", "B. Are", "C. Am", "D. Be"]'::jsonb, 'B', 1, '主詞 you 配 Are。'),
('elementary', 'Welcome ___ our school!', '["A. for", "B. to", "C. at", "D. on"]'::jsonb, 'B', 1, 'Welcome to + 地點為固定用法。'),
('elementary', 'Nice ___ meet you.', '["A. too", "B. to", "C. for", "D. of"]'::jsonb, 'B', 1, '初次見面固定句 Nice to meet you。'),
('elementary', 'See you ___.', '["A. tomorrow", "B. tomorrows", "C. in tomorrow", "D. at tomorrow"]'::jsonb, 'A', 0, '明天見用 tomorrow。'),
('elementary', '___ is this? — It''s a ruler.', '["A. What", "B. Who", "C. Where", "D. How"]'::jsonb, 'A', 0, '詢問物品是什麼用 What。'),
('elementary', '___ is he from? — Taiwan.', '["A. What", "B. Where", "C. When", "D. Why"]'::jsonb, 'B', 1, '詢問來自哪裡用 Where。'),
('elementary', 'I like ___ because it''s sweet.', '["A. candy", "B. salt", "C. spicy", "D. sour"]'::jsonb, 'A', 0, '甜的東西符合 candy。'),
('elementary', 'We wear coats when it''s ___.', '["A. hot", "B. cold", "C. sunny", "D. warm"]'::jsonb, 'B', 1, '穿外套通常是天冷時。'),
('elementary', 'Monday comes ___ Sunday.', '["A. before", "B. after", "C. at", "D. on"]'::jsonb, 'B', 1, '星期一在星期日之後。'),
('elementary', 'There are seven ___ in a week.', '["A. hours", "B. days", "C. months", "D. years"]'::jsonb, 'B', 1, '一週有七天 days。'),
('elementary', 'January is the first ___ of the year.', '["A. week", "B. day", "C. month", "D. season"]'::jsonb, 'C', 2, '一月是一年中的第一個月。'),
('elementary', 'Red and yellow make ___.', '["A. green", "B. orange", "C. purple", "D. black"]'::jsonb, 'B', 1, '紅加黃成橙色（題目常識）。'),
('elementary', 'A dog says ___.', '["A. meow", "B. woof", "C. moo", "D. oink"]'::jsonb, 'B', 1, '狗叫聲常用 woof。'),
('elementary', 'An elephant is ___.', '["A. small", "B. tiny", "C. large", "D. short"]'::jsonb, 'C', 2, '大象體型大，選 large。'),
('elementary', 'We use ___ to cut paper.', '["A. a spoon", "B. a fork", "C. scissors", "D. a plate"]'::jsonb, 'C', 2, '剪刀剪裁紙張。'),
('elementary', 'You read books in the ___.', '["A. kitchen", "B. classroom", "C. library", "D. gym"]'::jsonb, 'C', 2, '在圖書館閱讀。'),
('elementary', 'Doctors work in a ___.', '["A. school", "B. hospital", "C. farm", "D. zoo"]'::jsonb, 'B', 1, '醫師在醫院工作。'),
('elementary', 'An orange is usually ___.', '["A. blue", "B. orange", "C. black", "D. white"]'::jsonb, 'B', 1, '橘子通常橙色。'),
('elementary', 'We sleep in the ___.', '["A. kitchen", "B. garden", "C. bedroom", "D. street"]'::jsonb, 'C', 2, '在臥房睡覺。'),
('elementary', 'The opposite of ''big'' is ___.', '["A. large", "B. huge", "C. small", "D. tall"]'::jsonb, 'C', 2, 'big 的反義是 small。'),
('elementary', '12 minus 5 equals ___.', '["A. five", "B. six", "C. seven", "D. eight"]'::jsonb, 'C', 2, '12-5=7。'),
('elementary', 'Which season is the hottest?', '["A. spring", "B. summer", "C. fall", "D. winter"]'::jsonb, 'B', 1, '通常夏季最熱。'),
('elementary', 'You drink soup with a ___.', '["A. knife", "B. spoon", "C. chopsticks", "D. cup"]'::jsonb, 'B', 1, '湯一般用湯匙。'),
('elementary', 'A triangle has ___ sides.', '["A. two", "B. three", "C. four", "D. five"]'::jsonb, 'B', 1, '三角形有三邊。'),
('elementary', 'We celebrate Christmas in ___.', '["A. July", "B. December", "C. March", "D. June"]'::jsonb, 'B', 1, '聖誕節在十二月。'),
('elementary', 'A week has ___ days.', '["A. five", "B. six", "C. seven", "D. eight"]'::jsonb, 'C', 2, '一週七天。'),
('elementary', 'The first month is ___.', '["A. February", "B. January", "C. March", "D. April"]'::jsonb, 'B', 1, '第一個月是一月。'),
('elementary', 'If you are thirsty, you should ___.', '["A. sleep", "B. drink water", "C. run", "D. sing"]'::jsonb, 'B', 1, '口渴應喝水。'),
('elementary', 'Good night means we say it ___.', '["A. in the morning", "B. before sleep", "C. at lunch", "D. in class"]'::jsonb, 'B', 1, '晚安在睡前說。'),
('elementary', 'We write with a ___.', '["A. plate", "B. pen", "C. spoon", "D. chair"]'::jsonb, 'B', 1, '用筆書寫。'),
('elementary', 'Which animal can swim?', '["A. bird only", "B. fish", "C. only cats", "D. only cows"]'::jsonb, 'B', 1, '魚會游泳。'),
('elementary', 'Please ___ your teacher.', '["A. ignore", "B. respect", "C. shout at", "D. fight"]'::jsonb, 'B', 1, '應尊敬老師。'),
('elementary', '___ comes after Tuesday.', '["A. Monday", "B. Wednesday", "C. Sunday", "D. Friday"]'::jsonb, 'B', 1, '週三在週二之後。'),
('elementary', 'We eat rice with ___.', '["A. only hands in class", "B. chopsticks in many places", "C. never", "D. shoes"]'::jsonb, 'B', 1, '許多地區用筷子吃飯。'),
('elementary', '___ means ''Not bad.'' in many chats.', '["A. Terrible", "B. So-so", "C. Perfect", "D. Excellent"]'::jsonb, 'B', 1, 'So-so 表示普通、還可以。'),
('elementary', 'Turn left means go to the ___.', '["A. right side", "B. left side", "C. back only", "D. sky"]'::jsonb, 'B', 1, '左轉即往左邊。'),
('junior', 'If it rains tomorrow, we ___ the picnic.', '["A. cancel", "B. cancelled", "C. have cancelled", "D. will cancel"]'::jsonb, 'D', 3, '第一條件句：if + 現在簡單，主句用未來 will。'),
('junior', 'She ___ English for five years.', '["A. studies", "B. has studied", "C. studied", "D. is studying"]'::jsonb, 'B', 1, 'for + 一段時間表從過去持續至今，常用現在完成式。'),
('junior', 'By next July, he ___ here for ten years.', '["A. lives", "B. will live", "C. will have lived", "D. lived"]'::jsonb, 'C', 2, 'By + 未來時間點表「到那時將已…」，用未來完成式。'),
('junior', 'I wish I ___ taller.', '["A. am", "B. was", "C. were", "D. be"]'::jsonb, 'C', 2, 'wish 後假設與現在事實相反，be 動詞常用 were。'),
('junior', 'It''s time we ___ home.', '["A. go", "B. went", "C. gone", "D. going"]'::jsonb, 'B', 1, 'It''s time (that) + 過去式表「該是…的時候了」。'),
('junior', 'The book ___ by millions of readers.', '["A. reads", "B. is read", "C. was reading", "D. has read"]'::jsonb, 'B', 1, '書被閱讀，被動語態。'),
('junior', 'He decided ___ abroad.', '["A. study", "B. studying", "C. to study", "D. studied"]'::jsonb, 'C', 2, 'decide 後接不定詞 to study。'),
('junior', 'She is interested ___ music.', '["A. on", "B. at", "C. in", "D. for"]'::jsonb, 'C', 2, 'be interested in 為固定搭配。'),
('junior', 'Neither Tom nor his brothers ___ coming.', '["A. is", "B. are", "C. was", "D. be"]'::jsonb, 'B', 1, 'Neither nor 動詞與最近主詞 brothers 一致。'),
('junior', 'Not only Jane but also her friends ___ there.', '["A. was", "B. were", "C. is", "D. be"]'::jsonb, 'B', 1, 'Not only but also 動詞與較近主詞 friends 一致。'),
('junior', 'The news ___ surprising.', '["A. are", "B. were", "C. is", "D. be"]'::jsonb, 'C', 2, 'news 為不可數，視為單數。'),
('junior', 'Mathematics ___ my favorite subject.', '["A. are", "B. were", "C. is", "D. be"]'::jsonb, 'C', 2, '學科 mathematics 當單數。'),
('junior', 'Few students finished it; ___, most gave up.', '["A. therefore", "B. moreover", "C. however", "D. for example"]'::jsonb, 'C', 2, '語意轉折，用 however。'),
('junior', 'She runs fast; ___, she won the race.', '["A. but", "B. therefore", "C. although", "D. unless"]'::jsonb, 'B', 1, '因果：跑得快因此獲勝，用 therefore。'),
('junior', '___ it was cold, we went swimming.', '["A. Because", "B. Although", "C. If", "D. Unless"]'::jsonb, 'B', 1, '儘管冷還是去游泳，讓步用 Although。'),
('junior', 'You ___ smoke here; it''s forbidden.', '["A. must", "B. mustn''t", "C. should", "D. might"]'::jsonb, 'B', 1, '禁止用 mustn''t。'),
('junior', 'You ___ see a doctor if the pain continues.', '["A. mustn''t", "B. should", "C. might not", "D. couldn''t"]'::jsonb, 'B', 1, '建議應該看醫生用 should。'),
('junior', 'He speaks ___ he were an expert.', '["A. even if", "B. as though", "C. unless", "D. until"]'::jsonb, 'B', 1, '好像、彷彿用 as though / as if。'),
('junior', 'No sooner ___ than the phone rang.', '["A. he sat down", "B. had he sat down", "C. he had sat down", "D. did he sat down"]'::jsonb, 'B', 1, 'No sooner 倒裝且過去完成。'),
('junior', 'Scarcely ___ when the lights went out.', '["A. the show began", "B. had the show begun", "C. did the show began", "D. the show had begun"]'::jsonb, 'B', 1, 'Scarcely...when 結構常用過去完成倒裝。'),
('junior', 'I''d rather you ___ now.', '["A. leave", "B. left", "C. leaving", "D. to leave"]'::jsonb, 'B', 1, 'would rather + 子句表對他人行為願望時常用過去式。'),
('junior', 'If I ___ you, I would apologize.', '["A. am", "B. was", "C. were", "D. had been"]'::jsonb, 'C', 2, '與現在事實相反的第二條件 if I were you。'),
('junior', 'The man ___ wallet was stolen reported it.', '["A. who", "B. whom", "C. whose", "D. which"]'::jsonb, 'C', 2, '所有格關係代名詞 whose。'),
('junior', 'This is the best film ___ I have ever seen.', '["A. which", "B. that", "C. what", "D. who"]'::jsonb, 'B', 1, '先行詞有最高級修飾時關係代名詞常用 that。'),
('junior', 'He has three brothers, all of ___ are doctors.', '["A. them", "B. which", "C. whom", "D. who"]'::jsonb, 'C', 2, '介詞 + whom 指人（brothers）。'),
('junior', 'She suggested that he ___ early.', '["A. leave", "B. leaves", "C. left", "D. leaving"]'::jsonb, 'A', 0, 'suggest that + 原形動詞（英式／正式）或 should leave。'),
('junior', 'It''s essential that he ___ on time.', '["A. be", "B. is", "C. was", "D. will be"]'::jsonb, 'A', 0, 'essential that + (should) + 原形。'),
('junior', 'Hardly ___ when she started to cry.', '["A. the movie began", "B. had the movie begun", "C. did the movie began", "D. the movie had begun"]'::jsonb, 'B', 1, 'Hardly...when 與過去完成倒裝。'),
('junior', 'So difficult ___ that nobody solved it.', '["A. the problem was", "B. was the problem", "C. did the problem be", "D. the problem is"]'::jsonb, 'B', 1, 'So + 形／副 前置倒裝。'),
('junior', 'Not until yesterday ___ the truth.', '["A. I knew", "B. did I know", "C. I had known", "D. had I knew"]'::jsonb, 'B', 1, 'Not until 開頭需倒裝。'),
('junior', 'The cake smells ___.', '["A. nicely", "B. good", "C. well", "D. best"]'::jsonb, 'B', 1, '感官動詞 smell 後接形容詞 good。'),
('junior', 'He felt ___ about failing the exam.', '["A. badly", "B. bad", "C. worst", "D. badder"]'::jsonb, 'B', 1, 'feel 後接形容詞 bad。'),
('junior', 'She looked ___ at him.', '["A. angry", "B. angrily", "C. anger", "D. angrier"]'::jsonb, 'B', 1, '修飾動詞 look 用副詞 angrily。'),
('junior', 'I look forward ___ from you.', '["A. to hear", "B. to hearing", "C. hearing", "D. hear"]'::jsonb, 'B', 1, 'look forward to + 動名詞。'),
('junior', 'She accused him ___ lying.', '["A. for", "B. of", "C. with", "D. about"]'::jsonb, 'B', 1, 'accuse someone of + 動名詞。'),
('junior', 'You''d better ___ now.', '["A. to leave", "B. leave", "C. leaving", "D. left"]'::jsonb, 'B', 1, 'had better 後接動詞原形。'),
('junior', 'It''s no use ___ over spilt milk.', '["A. cry", "B. to cry", "C. crying", "D. cried"]'::jsonb, 'C', 2, 'It''s no use + 動名詞。'),
('junior', 'The problem ___ at the meeting yesterday.', '["A. discusses", "B. was discussed", "C. discussed", "D. is discussing"]'::jsonb, 'B', 1, '問題被討論，過去被動。'),
('junior', 'The teacher made the students ___ quietly.', '["A. to sit", "B. sit", "C. sitting", "D. sat"]'::jsonb, 'B', 1, 'make + 受詞 + 原形動詞。'),
('junior', 'Let me ___ you with your bags.', '["A. to help", "B. help", "C. helping", "D. helped"]'::jsonb, 'B', 1, 'let + 受詞 + 原形動詞。'),
('junior', 'He used ___ in Paris.', '["A. living", "B. to live", "C. live", "D. lived"]'::jsonb, 'B', 1, 'used to + 原形表過去習慣。'),
('junior', 'The boy ___ window was broken must pay.', '["A. who", "B. whom", "C. whose", "D. which"]'::jsonb, 'C', 2, '男孩之窗戶，用 whose。'),
('junior', 'This is the house ___ Shakespeare was born.', '["A. which", "B. where", "C. that", "D. what"]'::jsonb, 'B', 1, '地點先行詞用 where。'),
('junior', 'I don''t know ___ he will come.', '["A. if", "B. that", "C. what", "D. which"]'::jsonb, 'A', 0, 'whether/if 引導名詞子句表「是否」。'),
('junior', 'Tell me ___ you want.', '["A. what", "B. that", "C. which", "D. what that"]'::jsonb, 'A', 0, '疑問詞 what 作 want 的受詞。'),
('junior', '___ breaks the rules will be punished.', '["A. Whoever", "B. Who", "C. Whom", "D. Whose"]'::jsonb, 'A', 0, '無論誰違規，用 whoever。'),
('junior', '___ difficult the task is, we must finish it.', '["A. However", "B. Whatever", "C. Although", "D. Though"]'::jsonb, 'A', 0, 'However + 形／副 表「無論多…」。'),
('junior', 'He is ___ smart that everyone admires him.', '["A. so", "B. such", "C. very", "D. too"]'::jsonb, 'A', 0, 'so...that 結果子句。'),
('junior', 'It was ___ a cold day that we stayed inside.', '["A. so", "B. such", "C. very", "D. much"]'::jsonb, 'B', 1, 'such + a + 形 + 名。'),
('junior', 'By the time we arrived, the film ___.', '["A. starts", "B. had started", "C. has started", "D. was starting"]'::jsonb, 'B', 1, '動作發生在 arrived 之前，過去完成。'),
('junior', 'She ___ the essay before the deadline.', '["A. has finished", "B. had finished", "C. finished", "D. finishes"]'::jsonb, 'B', 1, '在過去某點之前已完成，過去完成。'),
('junior', 'If I ___ harder, I would have passed.', '["A. study", "B. studied", "C. had studied", "D. have studied"]'::jsonb, 'C', 2, '與過去事實相反的第三條件。'),
('junior', 'The letter ___ last week.', '["A. sends", "B. was sent", "C. is sending", "D. has sent"]'::jsonb, 'B', 1, '信被寄出，過去被動。'),
('junior', 'He enjoys ___, not to be read to.', '["A. to read", "B. reading", "C. read", "D. reads"]'::jsonb, 'B', 1, 'enjoy + 動名詞。'),
('junior', 'Would you mind ___ the door?', '["A. close", "B. closing", "C. to close", "D. closed"]'::jsonb, 'B', 1, 'mind + 動名詞。'),
('junior', 'It''s worth ___ again.', '["A. try", "B. trying", "C. to try", "D. tried"]'::jsonb, 'B', 1, 'worth + 動名詞。'),
('junior', 'She denied ___ the money.', '["A. steal", "B. stealing", "C. to steal", "D. stole"]'::jsonb, 'B', 1, 'deny + 動名詞。'),
('junior', 'I can''t afford ___ a new car.', '["A. buy", "B. to buy", "C. buying", "D. bought"]'::jsonb, 'B', 1, 'afford + to + 原形。'),
('junior', 'She reminded me ___ the lights.', '["A. turn off", "B. to turn off", "C. turning off", "D. of turn off"]'::jsonb, 'B', 1, 'remind + 受詞 + to + 原形。'),
('junior', 'He congratulated me ___ the prize.', '["A. for winning", "B. on winning", "C. to win", "D. of winning"]'::jsonb, 'B', 1, 'congratulate on + 動名詞。'),
('junior', 'She apologized ___ rude.', '["A. for being", "B. to be", "C. of being", "D. about be"]'::jsonb, 'A', 0, 'apologize for + 動名詞。'),
('junior', 'I''m thinking ___ abroad next year.', '["A. about going", "B. to go", "C. of go", "D. going"]'::jsonb, 'A', 0, 'think about + 動名詞。'),
('junior', 'He succeeded ___ the exam.', '["A. to pass", "B. in passing", "C. on passing", "D. pass"]'::jsonb, 'B', 1, 'succeed in + 動名詞。'),
('junior', 'She insisted ___ paying.', '["A. on", "B. for", "C. to", "D. of"]'::jsonb, 'A', 0, 'insist on + 動名詞。'),
('junior', 'He prevented me ___ leaving.', '["A. from", "B. to", "C. for", "D. of"]'::jsonb, 'A', 0, 'prevent from + 動名詞。'),
('junior', 'The rain stopped us ___ going out.', '["A. from", "B. to", "C. of", "D. for"]'::jsonb, 'A', 0, 'stop from + 動名詞。'),
('junior', 'She is capable ___ the job.', '["A. to do", "B. of doing", "C. for doing", "D. in do"]'::jsonb, 'B', 1, 'capable of + 動名詞。'),
('junior', 'He is used ___ early.', '["A. to get up", "B. to getting up", "C. of getting up", "D. for getting up"]'::jsonb, 'B', 1, 'be used to + 動名詞表習慣。'),
('junior', 'I''d prefer ___ at home tonight.', '["A. stay", "B. to stay", "C. staying", "D. stayed"]'::jsonb, 'B', 1, 'would prefer + to + 原形。'),
('junior', 'Rather than ___ , he walked.', '["A. wait", "B. to wait", "C. waiting", "D. waited"]'::jsonb, 'A', 0, 'rather than + 原形。'),
('junior', 'It ___ John who broke the vase.', '["A. is", "B. was", "C. were", "D. are"]'::jsonb, 'B', 1, '分裂句 It was... who，過去事件。'),
('junior', 'Little ___ about her past.', '["A. she knew", "B. did she know", "C. knew she", "D. she did know"]'::jsonb, 'B', 1, '否定副詞 Little 開頭倒裝。'),
('junior', 'Never ___ such a beautiful sunset.', '["A. I saw", "B. have I seen", "C. I have seen", "D. did I saw"]'::jsonb, 'B', 1, 'Never 開頭現在完成倒裝。'),
('junior', 'The more you practice, ___ you become.', '["A. the more fluently", "B. the more fluent", "C. more fluent", "D. most fluent"]'::jsonb, 'B', 1, 'the more... the more 平行結構。'),
('junior', 'He speaks English ___ a native speaker.', '["A. as fluent as", "B. as fluently as", "C. so fluent as", "D. more fluent than"]'::jsonb, 'B', 1, '修飾動詞 speaks 用副詞比較 as fluently as。'),
('college', 'The hypothesis was ___ by subsequent experiments.', '["A. refuted", "B. refuting", "C. refute", "D. to refute"]'::jsonb, 'A', 0, '被動語態，假設被後續實驗駁回。'),
('college', 'The study ___ a significant correlation between variables.', '["A. established", "B. establishing", "C. establish", "D. to establish"]'::jsonb, 'A', 0, '過去研究「確立」相關，用過去式 established。'),
('college', 'The author''s argument is somewhat ___.', '["A. tenuous", "B. tenuously", "C. tenuity", "D. tenuousness"]'::jsonb, 'A', 0, '形容詞作補語：論證略顯薄弱 tenuous。'),
('college', 'She gave a ___ account of the incident.', '["A. dispassionate", "B. dispassionately", "C. dispassion", "D. dispassioning"]'::jsonb, 'A', 0, '名詞前用形容詞：客觀平實的敘述。'),
('college', 'The policy has had ___ effects on small businesses.', '["A. deleterious", "B. deleteriously", "C. deleteriousness", "D. deleteriate"]'::jsonb, 'A', 0, '修飾名詞 effects 用形容詞 deleterious（有害）。'),
('college', 'Such behavior is ___ to the organization''s reputation.', '["A. inimical", "B. inimically", "C. inimic", "D. inimicality"]'::jsonb, 'A', 0, 'be inimical to 表示對…有害。'),
('college', 'The results were ___ unexpected.', '["A. wholly", "B. whole", "C. wholeness", "D. wholesome"]'::jsonb, 'A', 0, '修飾形容詞用副詞 wholly。'),
('college', 'The theory remains ___.', '["A. contentious", "B. contentiously", "C. content", "D. contention"]'::jsonb, 'A', 0, 'remain + 形容詞：仍有爭議 contentious。'),
('college', 'The paper lacks ___ rigor.', '["A. methodological", "B. methodologically", "C. methodology", "D. method"]'::jsonb, 'A', 0, '名詞前用形容詞 methodological。'),
('college', 'The evidence is ___.', '["A. inconclusive", "B. inconclusively", "C. inconclude", "D. inconclusiveness"]'::jsonb, 'A', 0, '形容詞作補語：證據尚無定論。'),
('college', 'He drew an ___ between the two cases.', '["A. analogy", "B. analogous", "C. analogously", "D. analog"]'::jsonb, 'A', 0, '不定冠詞後接名詞 analogy。'),
('college', 'The proposal was met with ___.', '["A. skepticism", "B. skeptical", "C. skeptically", "D. skeptic"]'::jsonb, 'A', 0, '介詞後接名詞 skepticism。'),
('college', 'The finding ___ previous assumptions.', '["A. contradicts", "B. contradict", "C. contradicting", "D. contradicted"]'::jsonb, 'A', 0, '主詞單數，現在式 contradicts。'),
('college', 'The variables were ___ controlled.', '["A. carefully", "B. careful", "C. carefulness", "D. care"]'::jsonb, 'A', 0, '修飾過去分詞 controlled 用副詞。'),
('college', 'The essay ___ several seminal works.', '["A. cites", "B. cite", "C. citing", "D. cited"]'::jsonb, 'A', 0, '現在簡單式或過去式；此處主詞第三人稱一般現在 cites。'),
('college', 'Scholars have long ___ this interpretation.', '["A. disputed", "B. dispute", "C. disputing", "D. disputes"]'::jsonb, 'A', 0, '現在完成式 have disputed。'),
('college', 'The narrative ___ chronologically.', '["A. unfolds", "B. unfold", "C. unfolding", "D. unfolded"]'::jsonb, 'A', 0, '主詞單數，敘述依時間展開 unfolds。'),
('college', 'The author ___ the reader''s expectations.', '["A. subverts", "B. subvert", "C. subverting", "D. subverted"]'::jsonb, 'A', 0, '第三人稱現在式 subverts。'),
('college', 'The critique is ___ superficial.', '["A. unduly", "B. undue", "C. undies", "D. undular"]'::jsonb, 'A', 0, '修飾形容詞 superficial 用副詞 unduly。'),
('college', 'The methodology is not ___ reproducible.', '["A. readily", "B. ready", "C. readiness", "D. reading"]'::jsonb, 'A', 0, '修飾形容詞用副詞 readily。'),
('college', 'The speaker ___ her main points clearly.', '["A. articulated", "B. articulate", "C. articulating", "D. articulates"]'::jsonb, 'A', 0, '過去演講用 articulated。'),
('college', 'The treaty ___ trade barriers.', '["A. dismantled", "B. dismantle", "C. dismantling", "D. dismantles"]'::jsonb, 'A', 0, '過去事件 dismantled。'),
('college', 'Inflation has ___ consumer confidence.', '["A. eroded", "B. erode", "C. eroding", "D. erodes"]'::jsonb, 'A', 0, '現在完成式 have eroded。'),
('college', 'The CEO ___ responsibility for the failure.', '["A. accepted", "B. accepts", "C. accepting", "D. accept"]'::jsonb, 'A', 0, '過去接受責任 accepted。'),
('college', 'The committee''s decision is ___.', '["A. binding", "B. bind", "C. bound", "D. binds"]'::jsonb, 'A', 0, '形容詞 binding 表示有約束力。'),
('college', 'The contract shall ___ on the first of July.', '["A. take effect", "B. take effects", "C. take affecting", "D. take effective"]'::jsonb, 'A', 0, '固定用法 take effect 生效。'),
('college', 'The plaintiff ___ damages.', '["A. sought", "B. seek", "C. seeking", "D. seeks"]'::jsonb, 'A', 0, '訴訟過去尋求賠償 sought。'),
('college', 'The court ___ the appeal.', '["A. dismissed", "B. dismiss", "C. dismissing", "D. dismisses"]'::jsonb, 'A', 0, '過去駁回 dismissed。'),
('college', 'The statute is ___ to interpretation.', '["A. subject", "B. subjective", "C. subjected", "D. subjecting"]'::jsonb, 'A', 0, 'be subject to 易於／須受…。'),
('college', 'Notwithstanding the risks, the board ___.', '["A. proceeded", "B. proceed", "C. proceeding", "D. proceeds"]'::jsonb, 'A', 0, '儘管風險仍進行，過去 proceeded。'),
('college', 'The data ___ systematically biased.', '["A. appear", "B. appears", "C. appearing", "D. appeared"]'::jsonb, 'A', 0, '將 data 當複數時動詞用 appear（亦有出版物視為單數而用 appears）。'),
('college', 'The phenomenon ___ further investigation.', '["A. warrants", "B. warrant", "C. warranting", "D. warranted"]'::jsonb, 'A', 0, '現象「值得」進一步調查，第三人稱 warrants。'),
('college', 'The implications are far-___.', '["A. reaching", "B. reached", "C. reach", "D. reaches"]'::jsonb, 'A', 0, '複合形容詞 far-reaching 深遠的。'),
('college', 'The argument ___ scrutiny.', '["A. withstands", "B. withstand", "C. withstanding", "D. withstood"]'::jsonb, 'A', 0, '第三人稱現在 withstands。'),
('college', 'The sample size is ___.', '["A. inadequate", "B. inadequately", "C. inadequacy", "D. inadequateness"]'::jsonb, 'A', 0, '形容詞補語 inadequate。'),
('college', 'The researchers ___ their conclusions cautiously.', '["A. stated", "B. state", "C. stating", "D. states"]'::jsonb, 'A', 0, '過去陳述 stated。'),
('college', 'The model ___ reality only partially.', '["A. reflects", "B. reflect", "C. reflecting", "D. reflected"]'::jsonb, 'A', 0, '現在式 reflects。'),
('college', 'The trend has ___ since 2020.', '["A. accelerated", "B. accelerate", "C. accelerating", "D. accelerates"]'::jsonb, 'A', 0, '現在完成式 has accelerated。'),
('college', 'The article ___ plagiarism in the draft.', '["A. alleged", "B. alleges", "C. allege", "D. alleging"]'::jsonb, 'A', 0, '過去報導 alleged。'),
('college', 'Prior ___ the meeting, circulate the agenda.', '["A. to", "B. than", "C. of", "D. for"]'::jsonb, 'A', 0, 'prior to 相當於 before。'),
('college', 'The ethics board rarely ___ approval without review.', '["A. withholds", "B. withhold", "C. withheld", "D. withholding"]'::jsonb, 'A', 0, '描述慣例用現在式 withholds。'),
('college', 'The manuscript was ___ peer review.', '["A. subjected to", "B. subject to", "C. subjecting to", "D. subjective to"]'::jsonb, 'A', 0, 'be subjected to 遭受到…審查。'),
('college', 'The speaker ___ an anecdote to illustrate the point.', '["A. invoked", "B. invoke", "C. invoking", "D. invokes"]'::jsonb, 'A', 0, '過去演講援引 invoked。'),
('college', 'The framework is ___ applicable across disciplines.', '["A. broadly", "B. broad", "C. broaden", "D. breadth"]'::jsonb, 'A', 0, '修飾形容詞 applicable 用副詞 broadly。'),
('college', 'The decline was ___ precipitous.', '["A. somewhat", "B. somewhatly", "C. some", "D. something"]'::jsonb, 'A', 0, '修飾形容詞 precipitous 用副詞 somewhat。'),
('college', 'The author ___ the limitations of the study.', '["A. acknowledges", "B. acknowledge", "C. acknowledging", "D. acknowledged"]'::jsonb, 'D', 3, '過去式 acknowledged 或現在 acknowledges；此處選 acknowledged 表文中承認。'),
('college', 'The policy ___ unintended consequences.', '["A. entailed", "B. entail", "C. entailing", "D. entails"]'::jsonb, 'A', 0, '過去造成 entailed。'),
('college', 'The dataset was ___ anonymized.', '["A. properly", "B. proper", "C. prop", "D. propriety"]'::jsonb, 'A', 0, '修飾過去分詞用副詞 properly。'),
('college', 'The reviewer questioned the paper''s ___.', '["A. coherence", "B. coherent", "C. coherently", "D. cohere"]'::jsonb, 'A', 0, '所有格後接名詞 coherence。'),
('college', 'The conclusion does not ___ follow from the premises.', '["A. necessarily", "B. necessary", "C. necessity", "D. necessitate"]'::jsonb, 'A', 0, '修飾動詞 follow 用副詞 necessarily。'),
('college', 'The theory was ___ received by peers.', '["A. well", "B. good", "C. best", "D. better"]'::jsonb, 'A', 0, '修飾過去分詞 received 用副詞 well。'),
('college', 'The grant ___ interdisciplinary collaboration.', '["A. fostered", "B. foster", "C. fostering", "D. fosters"]'::jsonb, 'A', 0, '過去促進 fostered。'),
('college', 'The lecture ___ key terminology.', '["A. clarified", "B. clarify", "C. clarifying", "D. clarifies"]'::jsonb, 'A', 0, '過去闡明 clarified。'),
('college', 'The experiment ___ a controlled environment.', '["A. used", "B. use", "C. using", "D. uses"]'::jsonb, 'A', 0, '過去使用 used。'),
('college', 'Participants were ___ at random.', '["A. assigned", "B. assign", "C. assigning", "D. assigns"]'::jsonb, 'A', 0, '過去分詞被指派 assigned。'),
('college', 'The survey ___ self-reported bias.', '["A. exhibits", "B. exhibit", "C. exhibiting", "D. exhibited"]'::jsonb, 'D', 3, '過去顯示 exhibited 或現在 exhibits；選 exhibited 表調查當時。'),
('college', 'The algorithm ___ faster convergence.', '["A. enabled", "B. enable", "C. enabling", "D. enables"]'::jsonb, 'A', 0, '過去使可能 enabled。'),
('college', 'The chapter ___ the historical context.', '["A. sketches", "B. sketch", "C. sketching", "D. sketched"]'::jsonb, 'D', 3, '過去概述 sketched。'),
('college', 'The index ___ several omissions.', '["A. contains", "B. contain", "C. containing", "D. contained"]'::jsonb, 'D', 3, '過去包含 contained。'),
('college', 'The keynote ___ the conference theme.', '["A. addressed", "B. address", "C. addressing", "D. addresses"]'::jsonb, 'A', 0, '過去呼應 addressed。'),
('college', 'The panel ___ for three hours.', '["A. lasted", "B. last", "C. lasting", "D. lasts"]'::jsonb, 'A', 0, '過去持續 lasted。'),
('college', 'The editor ___ the manuscript for clarity.', '["A. tightened", "B. tighten", "C. tightening", "D. tightens"]'::jsonb, 'A', 0, '過去修訂 tightened。'),
('college', 'The grant proposal was ___.', '["A. rejected", "B. reject", "C. rejecting", "D. rejects"]'::jsonb, 'A', 0, '被動過去分詞 rejected。'),
('college', 'The university ___ new admissions criteria.', '["A. adopted", "B. adopt", "C. adopting", "D. adopts"]'::jsonb, 'A', 0, '過去採納 adopted。'),
('college', 'The lecture hall was ___ full.', '["A. nearly", "B. near", "C. nearest", "D. nearer"]'::jsonb, 'A', 0, '修飾形容詞 full 用副詞 nearly。'),
('college', 'The article ___ a literature review.', '["A. includes", "B. include", "C. including", "D. included"]'::jsonb, 'D', 3, '過去包含 included。'),
('college', 'The seminar ___ graduate students only.', '["A. targeted", "B. target", "C. targeting", "D. targets"]'::jsonb, 'A', 0, '過去以…為對象 targeted。'),
('college', 'The findings need to be ___ in a larger sample.', '["A. replicated", "B. replicate", "C. replicating", "D. replicates"]'::jsonb, 'A', 0, '研究須在更大樣本中「重複驗證」。'),
('college', 'The paper ___ ethical approval before data collection.', '["A. obtained", "B. obtain", "C. obtaining", "D. obtains"]'::jsonb, 'A', 0, '過去取得倫理核准 obtained。'),
('college', 'The authors ___ any conflicts of interest.', '["A. disclosed", "B. disclose", "C. disclosing", "D. discloses"]'::jsonb, 'A', 0, '過去揭露利益衝突 disclosed。'),
('college', 'The discussion section ___ the results to theory.', '["A. relates", "B. relate", "C. relating", "D. related"]'::jsonb, 'D', 3, '過去將結果連結理論 related。'),
('college', 'Table 2 ___ descriptive statistics for each group.', '["A. summarizes", "B. summarize", "C. summarizing", "D. summarized"]'::jsonb, 'D', 3, '過去式 summarized 表列出／總述。'),
('college', 'The limitation ___ the cross-sectional design.', '["A. concerns", "B. concern", "C. concerning", "D. concerned"]'::jsonb, 'A', 0, '描述研究限制常用現在式 concerns，表示『此限制在於／涉及…』。'),
('college', 'Future research should ___ longitudinal methods.', '["A. employ", "B. employs", "C. employing", "D. employed"]'::jsonb, 'A', 0, '情態動詞後接原形 employ。'),
('college', 'The coefficient was statistically ___ at p < .05.', '["A. significant", "B. significantly", "C. significance", "D. signify"]'::jsonb, 'A', 0, '形容詞補語 significant 表示達顯著水準。'),
('professor', 'The term ''morpheme'' refers to ___.', '["A. a minimal meaningful unit", "B. a speech sound", "C. a dialect variant", "D. a writing system"]'::jsonb, 'A', 0, '語言學中 morpheme 為最小有意義單位。'),
('professor', 'A phoneme is best described as ___.', '["A. a letter of the alphabet", "B. a contrastive sound category", "C. a syllable", "D. a stress pattern"]'::jsonb, 'B', 1, '音位是具區別意義功能的音類別。'),
('professor', 'In linguistics, ''syntax'' concerns ___.', '["A. word meanings", "B. sentence structure", "C. sound patterns", "D. language history"]'::jsonb, 'B', 1, '句法研究句子結構。'),
('professor', 'Semantics primarily deals with ___.', '["A. pronunciation", "B. meaning", "C. spelling reform", "D. orthography"]'::jsonb, 'B', 1, '語義學研究意義。'),
('professor', 'Pragmatics focuses on ___.', '["A. sentence length", "B. language use in context", "C. phonetic transcription", "D. etymology"]'::jsonb, 'B', 1, '語用學關注語境中的使用。'),
('professor', 'An example of a polyseme is ''bank'' meaning river edge and financial institution; this illustrates ___.', '["A. homophony", "B. polysemy", "C. synonymy", "D. antonymy"]'::jsonb, 'B', 1, '同一詞形多義為 polysemy。'),
('professor', 'If two words sound identical but differ in meaning and spelling, they are ___.', '["A. synonyms", "B. homophones", "C. hypernyms", "D. collocations"]'::jsonb, 'B', 1, '同音異義為 homophones。'),
('professor', 'The study of word origins is ___.', '["A. syntax", "B. phonology", "C. etymology", "D. morphology"]'::jsonb, 'C', 2, '詞源研究為 etymology。'),
('professor', 'In English, ''unhappiness'' contains ___.', '["A. one morpheme", "B. two morphemes", "C. three morphemes", "D. four morphemes"]'::jsonb, 'C', 2, 'un + happy + ness 三個詞素。'),
('professor', 'Which pair illustrates phonemic contrast (minimal pairs)?', '["A. pin vs spin /p/", "B. pit vs bit /p/-/b/", "C. cat vs cats /s/-/z/", "D. ship vs sheep"]'::jsonb, 'B', 1, 'pit / bit 僅差一個音位 /p/ 與 /b/，為最小對立組，顯示音位對立。'),
('professor', 'A prescriptive rule tells speakers ___.', '["A. how language is actually used", "B. how they ought to use language", "C. how babies acquire language", "D. how dialects spread"]'::jsonb, 'B', 1, '規範語法規定「應如何」使用。'),
('professor', 'Descriptive linguistics aims to ___.', '["A. rank languages", "B. describe actual usage", "C. ban loanwords", "D. fix spelling"]'::jsonb, 'B', 1, '描寫語言學描述實際用法。'),
('professor', 'The sapir-whorf hypothesis concerns ___.', '["A. sound symbolism", "B. language and thought", "C. language families", "D. writing direction"]'::jsonb, 'B', 1, '薩丕爾—沃夫假設探討語言與思維。'),
('professor', 'Metonymy is exemplified by ___.', '["A. ''kick the bucket''", "B. The crown announced...", "C. It''s raining cats and dogs", "D. Time flies"]'::jsonb, 'B', 1, 'The crown 借代王室為 metonymy。'),
('professor', 'A mixed metaphor is problematic because it ___.', '["A. uses passive voice", "B. combines clashing images", "C. is too short", "D. lacks a thesis"]'::jsonb, 'B', 1, '混合隱喻意象衝突。'),
('professor', 'Zeugma joins ___.', '["A. two unrelated metaphors", "B. one word with two objects in different senses", "C. two synonyms", "D. subject and object"]'::jsonb, 'B', 1, '軛式搭配一詞配兩受詞不同義。'),
('professor', 'Chiasmus involves ___.', '["A. rhyme", "B. reversed grammatical structure", "C. alliteration", "D. omission of vowels"]'::jsonb, 'B', 1, '交錯配列為結構倒序對照。'),
('professor', 'Asyndeton omits ___.', '["A. verbs", "B. subjects", "C. conjunctions", "D. articles"]'::jsonb, 'C', 2, '連珠式省略連接詞。'),
('professor', 'Polysyndeton repeats ___.', '["A. subjects", "B. conjunctions", "C. prepositions", "D. articles"]'::jsonb, 'B', 1, '連綴式重複連接詞。'),
('professor', 'Anaphora is ___.', '["A. end rhyme", "B. repetition at the start of successive clauses", "C. use of foreign words", "D. inversion only"]'::jsonb, 'B', 1, '首語重複為句首重複。'),
('professor', 'Catachresis refers to ___.', '["A. correct grammar", "B. strained or improper metaphor", "C. metrical feet", "D. IPA notation"]'::jsonb, 'B', 1, '誤喻為不當或過度延伸隱喻。'),
('professor', 'Synecdoche uses ___.', '["A. rhyme", "B. a part for the whole or vice versa", "C. homophones", "D. palindrome"]'::jsonb, 'B', 1, '提喻以部分代整體或反之。'),
('professor', 'Litotes expresses affirmation through ___.', '["A. hyperbole", "B. double negation or understatement", "C. simile", "D. allusion"]'::jsonb, 'B', 1, '曲言法以否定或輕描淡寫表肯定。'),
('professor', 'Pejorative connotation means the word feels ___.', '["A. neutral", "B. positive", "C. negative", "D. technical"]'::jsonb, 'C', 2, '貶義為負面色彩。'),
('professor', 'If an argument affirms the consequent, it is ___.', '["A. valid", "B. sound", "C. formally invalid", "D. inductive only"]'::jsonb, 'C', 2, '肯定後件為形式謬誤。'),
('professor', 'Denying the antecedent is ___.', '["A. always valid", "B. formally invalid", "C. the same as modus ponens", "D. a strong analogy"]'::jsonb, 'B', 1, '否定前件為無效推論。'),
('professor', 'A deductively valid argument can still be ___.', '["A. unsound if premises are false", "B. always sound", "C. inductive", "D. self-refuting always"]'::jsonb, 'A', 0, '有效論證若前提假仍可 unsound。'),
('professor', 'An ad hoc rescue revises a theory ___.', '["A. before testing", "B. only to protect it from falsification", "C. using statistics only", "D. through translation"]'::jsonb, 'B', 1, '特設性防衛為免於被否證而補救。'),
('professor', 'Straw man fallacy involves ___.', '["A. using analogies", "B. misrepresenting an opponent''s view", "C. appealing to pity", "D. equivocation only"]'::jsonb, 'B', 1, '稻草人謬誤扭曲對方論點。'),
('professor', 'Equivocation shifts ___.', '["A. tenses", "B. the meaning of a key term", "C. font size", "D. sample size"]'::jsonb, 'B', 1, '歧義謬誤偷換關鍵詞義。'),
('professor', 'Post hoc ergo propter hoc mistakes ___.', '["A. correlation for authentication", "B. sequence for causation", "C. cause for correlation", "D. definition for example"]'::jsonb, 'B', 1, '後此謬誤把先後當因果。'),
('professor', 'Begging the question ___.', '["A. asks politely", "B. assumes the conclusion in premises", "C. uses only empirical data", "D. avoids pronouns"]'::jsonb, 'B', 1, '循環論證把結論藏於前提。'),
('professor', 'The word ''otiose'' most nearly means ___.', '["A. meticulous", "B. superfluous", "C. rapid", "D. fragrant"]'::jsonb, 'B', 1, 'otiose 意為多餘、無用。'),
('professor', 'The word ''perspicacious'' suggests ___.', '["A. sloppy thinking", "B. keen insight", "C. physical strength", "D. anger"]'::jsonb, 'B', 1, 'perspicacious 表示敏銳洞察。'),
('professor', 'The word ''recalcitrant'' fits ___.', '["A. a willing volunteer", "B. a stubborn resistor", "C. a transparent liquid", "D. a cheap fabric"]'::jsonb, 'B', 1, 'recalcitrant 形容頑抗不服。'),
('professor', 'The word ''sycophant'' denotes ___.', '["A. a wise teacher", "B. a servile flatterer", "C. a neutral judge", "D. a brave pioneer"]'::jsonb, 'B', 1, 'sycophant 為阿諛奉承者。'),
('professor', 'The word ''laconic'' describes speech that is ___.', '["A. lengthy", "B. brief", "C. loud", "D. archaic"]'::jsonb, 'B', 1, 'laconic 表示簡潔寡言。'),
('professor', 'The idiom ''to pull someone''s leg'' means ___.', '["A. to help them walk", "B. to tease or joke", "C. to betray them", "D. to lend money"]'::jsonb, 'B', 1, '英式幽默表示開玩笑、捉弄。'),
('professor', 'The idiom ''bury the hatchet'' means ___.', '["A. hide tools", "B. make peace", "C. start a fight", "D. plant trees"]'::jsonb, 'B', 1, '言歸於好、止息爭端。'),
('professor', 'The idiom ''let sleeping dogs lie'' advises ___.', '["A. wake pets", "B. avoid stirring up trouble", "C. train animals", "D. sleep more"]'::jsonb, 'B', 1, '勿挑起不必要的麻煩。'),
('professor', 'The idiom ''the ball is in your court'' means ___.', '["A. play tennis", "B. it''s your turn to act", "C. you lost", "D. the game ended"]'::jsonb, 'B', 1, '輪到你採取行動。'),
('professor', 'The idiom ''cut corners'' suggests ___.', '["A. meticulous work", "B. doing something hastily or improperly", "C. taking a shortcut road only", "D. building squares"]'::jsonb, 'B', 1, '偷工減料、走捷徑敷衍。'),
('professor', 'An oxymoron pairs ___.', '["A. synonyms", "B. contradictory terms", "C. foreign words", "D. rhyming words"]'::jsonb, 'B', 1, '矛盾修辭並置相反概念。'),
('professor', 'Epistemic modality expresses ___.', '["A. obligation about the past", "B. speaker''s degree of commitment to truth", "C. physical ability only", "D. future tense only"]'::jsonb, 'B', 1, '認識情態表說話者對命題真假的確信度。'),
('professor', 'Deictic expressions depend on ___.', '["A. Latin roots", "B. utterance context", "C. metrical stress", "D. silent letters"]'::jsonb, 'B', 1, '指示詞依賴語境座標。'),
('professor', 'A minimal pair in phonology demonstrates ___.', '["A. free variation", "B. phonemic contrast", "C. allophony only", "D. tone sandhi"]'::jsonb, 'B', 1, '最小對立組顯示音位對立。'),
('professor', 'Complementary distribution typically indicates ___.', '["A. phonemes", "B. allophones of one phoneme", "C. minimal pairs", "D. word stress"]'::jsonb, 'B', 1, '互補分布多為同一音位之變體。'),
('professor', 'The passive voice is sometimes preferred in scientific writing to ___.', '["A. increase wordiness", "B. foreground the process or result", "C. avoid verbs", "D. hide subject always"]'::jsonb, 'B', 1, '被動可突出過程或結果。'),
('professor', 'The rhetorical question primarily functions to ___.', '["A. request information only", "B. prompt reflection rather than an answer", "C. change tense", "D. translate literally"]'::jsonb, 'B', 1, '反問用於引發思考而非真問。'),
('professor', 'Pathos appeals to ___.', '["A. logic", "B. credibility", "C. emotion", "D. grammar"]'::jsonb, 'C', 2, '悲情訴諸情感 pathos。'),
('professor', 'Logos appeals to ___.', '["A. emotion", "B. character", "C. reasoning and evidence", "D. rhythm"]'::jsonb, 'C', 2, '理性訴諸論證 logos。'),
('professor', 'Ethos appeals to ___.', '["A. statistics only", "B. speaker credibility", "C. musicality", "D. imagery only"]'::jsonb, 'B', 1, '人格訴諸可信度 ethos。'),
('professor', 'Ambiguity of scope may confuse whether ___.', '["A. a verb is transitive", "B. negation applies to one clause or another", "C. nouns are plural", "D. letters are silent"]'::jsonb, 'B', 1, '範域歧義影響否定範圍。'),
('professor', 'Vagueness differs from ambiguity because vagueness ___.', '["A. has two precise senses", "B. involves borderline cases", "C. is always grammatical", "D. requires synonyms"]'::jsonb, 'B', 1, '模糊涉及界線案例而非雙義。'),
('professor', 'Performative utterances ___.', '["A. cannot be spoken", "B. do something by being said", "C. only describe weather", "D. lack verbs"]'::jsonb, 'B', 1, '施為句以說出即完成行為。'),
('professor', 'Implicature (Gricean) relies on ___.', '["A. literal grammar only", "B. conversational cooperation and context", "C. spelling rules", "D. IPA charts"]'::jsonb, 'B', 1, '含意依合作原則與語境推導。'),
('professor', 'A malapropism is ___.', '["A. a deliberate pun", "B. an amusing word substitution error", "C. a silent letter", "D. a dialect map"]'::jsonb, 'B', 1, '誤用近似音詞造成滑稽效果。'),
('professor', 'Proprioceptive imagery appeals to ___.', '["A. sight", "B. internal bodily sensation", "C. hearing", "D. taste only"]'::jsonb, 'B', 1, '本體感覺意象描寫身體內部感覺。'),
('professor', 'Synesthesia in literature ___.', '["A. avoids metaphor", "B. crosses sensory domains", "C. uses only facts", "D. removes adjectives"]'::jsonb, 'B', 1, '通感跨感官域。'),
('professor', 'The hedging phrase ''I might be wrong, but...'' serves to ___.', '["A. assert certainty", "B. soften the claim", "C. change topic", "D. quote sources"]'::jsonb, 'B', 1, '模糊限制語弱化斷言。'),
('professor', 'Parallelism in prose primarily enhances ___.', '["A. confusion", "B. rhythm and clarity", "C. spelling", "D. font choice"]'::jsonb, 'B', 1, '排比增節奏與清晰度。'),
('professor', 'Antimetabole repeats words in ___.', '["A. random order", "B. reverse order", "C. alphabetical order", "D. silent letters"]'::jsonb, 'B', 1, '逆序重複為 antimetabole。'),
('professor', 'The pathetic fallacy attributes human emotion to ___.', '["A. numbers", "B. nature or objects", "C. verbs only", "D. footnotes"]'::jsonb, 'B', 1, '感情誤置賦予自然或物情感。'),
('professor', 'An enthymeme in rhetoric is ___.', '["A. a long poem", "B. a syllogism with an unstated premise", "C. a type of irony", "D. a grammar rule"]'::jsonb, 'B', 1, '省略三段論省略前提。'),
('professor', 'The distinction between ''fewer'' and ''less'' is prescriptively about ___.', '["A. formality", "B. count vs mass nouns", "C. British vs American", "D. past vs present"]'::jsonb, 'B', 1, '規範上 fewer 配可數、less 配不可數。'),
('professor', 'In philosophy of language, ''extension'' of a term is ___.', '["A. its intension", "B. the set of things it denotes", "C. its etymology", "D. its pronunciation"]'::jsonb, 'B', 1, '外延為詞所指對象集合。'),
('professor', 'The intension of a word includes ___.', '["A. only pronunciation", "B. associative or definitional properties", "C. only spelling", "D. rhyme scheme"]'::jsonb, 'B', 1, '內涵為定義性質與屬性。'),
('professor', 'If P implies Q, then ''not Q'' implies ___.', '["A. P", "B. not P", "C. Q", "D. P and Q"]'::jsonb, 'B', 1, '拒取式：非 Q 則非 P（假設原為 P→Q）。'),
('professor', 'A contingent truth is one that ___.', '["A. must be true in all worlds", "B. could have been otherwise", "C. is self-contradictory", "D. only concerns math"]'::jsonb, 'B', 1, '偶然真理可以不是如此。'),
('professor', 'Analytic statements are often characterized as ___.', '["A. empirical", "B. true by virtue of meaning", "C. always false", "D. poetic"]'::jsonb, 'B', 1, '分析句依意義為真。'),
('professor', 'Synthetic statements ___.', '["A. are true by definition only", "B. combine concepts not contained in the subject", "C. cannot be false", "D. lack predicates"]'::jsonb, 'B', 1, '綜合句把主詞所無之概念連結起來。'),
('professor', 'The fallacy of composition assumes ___.', '["A. parts equal whole properties", "B. what is true of parts is true of the whole", "C. correlation implies causation", "D. experts are wrong"]'::jsonb, 'B', 1, '合成謬誤以部分性質推整體。'),
('professor', 'The fallacy of division assumes ___.', '["A. the whole''s property belongs to every part", "B. correlation is causation", "C. samples are random", "D. definitions shift"]'::jsonb, 'A', 0, '分割謬誤以整體屬性推每一部分。'),
('professor', 'A virtue of a clear operational definition is that it ___.', '["A. avoids all measurement", "B. makes variables observable and testable", "C. removes ethics", "D. eliminates theory"]'::jsonb, 'B', 1, '操作型定義使變項可觀測檢驗。'),
('professor', 'In academic hedging, the verb suggests is weaker than ___.', '["A. might", "B. proves", "C. could", "D. may"]'::jsonb, 'B', 1, 'suggests 比 proves 語氣弱。');
